/*
	Leader Text
	Authors: GameBoy2936
*/

INSERT INTO LocalizedText
			(Language, Tag, Text)
VALUES

-- Diplos | First Meet

	-- First AI Line (ANY)
	('en_US',	'LOC_DIPLO_FIRST_MEET_LEADER_AMERICA_ANY',
	'Welcome to the United States of America. If you conduct yourself well, you can consider us friends.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_LEADER_CANADA_ANY',
	'On behalf of the people of Canada, we bid you welcome to your country.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_LEADER_CHINA_PRC_ANY',
	'Welcome. We are the People’s Republic of China. We do not look for conflict with others, but we will respond forcefully to protect our interests.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_LEADER_FRANCE_ANY',
	'We are the French, and we welcome you to the realm. We do so look forward to learning all there is to know about you.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_LEADER_ICELAND_ANY',
	'Good day. We welcome your people to Iceland, and to our humble homestead.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_LEADER_INDIA_ANY',
	'In the name of the Indian people, we offer you our hand in friendship to your nation. It is great to meet you.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_LEADER_IRAN_ANY',
	'Peace be upon you! We are the country of Iran, true servants of Allah. We hope that you also walk on the right path.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_LEADER_ISRAEL_ANY',
	'Greetings! Welcome to Israel. If you will be a friend to our people, you will find us faithful allies.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_LEADER_ITALY_ANY',
	'Greetings. We are the Italian Republic. If you are a friend of Italy, be welcome.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_LEADER_MADAGASCAR_ANY',
	'Salama! Welcome to Madagascar, the land of lemurs and friendly citizens alike. Who are you?'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_LEADER_MALAYSIA_ANY',
	'Greetings, traveller! We are the nation of Malaysia. Tell us, what shores do you call your own?'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_LEADER_NETHERLANDS_ANY',
	'We are the Netherlands. Welcome! It is our great pleasure to finally meet you.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_LEADER_NEW_ZEALAND_ANY',
	'We are New Zealand, and we welcome you. Will you tell us about yourself?'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_LEADER_PAKISTAN_ANY',
	'Greetings, and welcome! We are the Islamic Republic of Pakistan. It is nice to meet you.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_LEADER_PHILIPPINES_ANY',
	'Welcome to the Philippines, kaibigan. It is a pleasure to meet you.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_LEADER_POLAND_ANY',
	'A meeting blessed by God, we’re sure. We are Poland, and look forward to learning about who you are.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_LEADER_THAILAND_ANY',
	'Greetings. We are the Kingdom of Thailand. You do our humble nation great honor by visiting us.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_LEADER_UKRAINE_ANY',
	'Hello, my friend! Ours and the people of Ukraine send their heartiest greetings to you. We look forward to getting to know you better!'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_LEADER_VIETNAM_ANY',
	'Good day. We are humbled to see you, and welcome to Vietnam. Who are you?'),
	
	-- AI invitation to visit nearby City (ANY)
	('en_US',	'LOC_DIPLO_FIRST_MEET_VISIT_RECIPIENT_LEADER_ARABIA_ANY',
	'We are honored to offer you the hospitality of our cities: the finest arts, the most delectable feasts, and the melodious adhan heard throughout. Would you care to visit?'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_VISIT_RECIPIENT_LEADER_AUSTRALIA_ANY',
	'If you see fit, we’d ask that you visit our nearest city. Perhaps we can tempt you with some pavlova?'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_VISIT_RECIPIENT_LEADER_BRAZIL_ANY',
	'Come to Brazil! Do you know how to dance samba? It doesn’t matter, you will enjoy the Carnival regardless.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_VISIT_RECIPIENT_LEADER_CANADA_ANY',
	'Please come to visit the capital of Canada. Our people would be honored by your visit.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_VISIT_RECIPIENT_LEADER_CUBA_ANY',
	'We implore you to come visit Havana! You should partake in our world-known culture.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_VISIT_RECIPIENT_LEADER_ETHIOPIA_ANY',
	'We have spread a wide table with injera and laid upon it tibs and kitfo. Will you share a meal with us?'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_VISIT_RECIPIENT_LEADER_FRANCE_ANY',
	'There is a city of ours nearby. We invite you to visit, and enjoy the local French culture.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_VISIT_RECIPIENT_LEADER_GERMANY_ANY',
	'We have a city nearby. You are welcome to visit! Perhaps try some of the local beer, and have some schnitzel?'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_VISIT_RECIPIENT_LEADER_ICELAND_ANY',
	'We have a little settlement nearby. You should visit! We can’t have people saying that we Icelanders aren’t hospitable!'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_VISIT_RECIPIENT_LEADER_INDIA_ANY',
	'Come to our nearest city. It may be a little crowded, but it is vibrant and full of life.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_VISIT_RECIPIENT_LEADER_INDONESIA_ANY',
	'Our city is near. Come, you should visit! Take a walk through the kampung.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_VISIT_RECIPIENT_LEADER_MADAGASCAR_ANY',
	'You should come take a look at our nearby city. We can take you on a tour showcasing our wonderful landscapes and people.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_VISIT_RECIPIENT_LEADER_MALAYSIA_ANY',
	'If you wish, you may visit our city nearby. Take a rest, enjoy the hospitality, and share with us stories of your culture.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_VISIT_RECIPIENT_LEADER_MALI_ANY',
	'Please, come visit the nearby city of Mali! It is a place of great learning—and profit, too.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_VISIT_RECIPIENT_LEADER_NIGERIA_ANY',
	'Nigeria has a city nearby. If you come in friendship, we welcome you to visit.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_VISIT_RECIPIENT_LEADER_PAKISTAN_ANY',
	'You are near Pakistan. If you would like to visit one of our cities, you are welcome to stop in and partake of our hospitality. There’s a cricket game on to enjoy today.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_VISIT_RECIPIENT_LEADER_PHILIPPINES_ANY',
	'We would like to extend to you an invitation to visit our nearby city. Come, enjoy the culture and fine works of the Filipino people.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_VISIT_RECIPIENT_LEADER_POLAND_ANY',
	'We humbly invite you to be our guest of honor and join us in our nearby city. There is a festive folk dance we could enjoy.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_VISIT_RECIPIENT_LEADER_SOUTH_KOREA_ANY',
	'Since you’re close by, why don’t you give k-pop karaoke a try in our nearest city? We are sure they will give a warm welcome!'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_VISIT_RECIPIENT_LEADER_THAILAND_ANY',
	'We have a city nearby. Perhaps you’d be interested in joining us in some restful meditation? Then afterwards, we can show you around.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_VISIT_RECIPIENT_LEADER_TURKEY_ANY',
	'We would welcome your representatives to take in the sight of our nearest city, that they may be awed by its majesty.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_VISIT_RECIPIENT_LEADER_VIETNAM_ANY',
	'Welcome to Vietnam! Come and have some phở with us in our nearest city.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_VISIT_RECIPIENT_LEADER_UK_ANY',
	'One of our cities is nearby. You are welcome to stop by. You could visit the local pub and sample our hospitality?'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_VISIT_RECIPIENT_LEADER_UKRAINE_ANY',
	'Come, visit our nearby city! We are sure you will be pleased a nice stroll alongside one of our sunflower fields, after we show you around.'),
	
	-- AI accepts human invitation (ANY)
	('en_US',	'LOC_DIPLO_FIRST_MEET_NEAR_INITIATOR_POSITIVE_LEADER_AMERICA_ANY',
	'Can’t say no to that.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NEAR_INITIATOR_POSITIVE_LEADER_ARABIA_ANY',
	'A fruitful offer. May Allah bless you.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NEAR_INITIATOR_POSITIVE_LEADER_AUSTRALIA_ANY',
	'But of course! We look forward to seeing it in person.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NEAR_INITIATOR_POSITIVE_LEADER_CANADA_ANY',
	'Of course. Canada is grateful for your offer.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NEAR_INITIATOR_POSITIVE_LEADER_CUBA_ANY',
	'Yes. I would love to come and see your city.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NEAR_INITIATOR_POSITIVE_LEADER_ETHIOPIA_ANY',
	'Yes.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NEAR_INITIATOR_POSITIVE_LEADER_FRANCE_ANY',
	'By all means. It will be a pleasure to see your city growing up close.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NEAR_INITIATOR_POSITIVE_LEADER_GERMANY_ANY',
	'Thank you very much for the offer.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NEAR_INITIATOR_POSITIVE_LEADER_ICELAND_ANY',
	'Yes! It will be excellent seeing new lands!'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NEAR_INITIATOR_POSITIVE_LEADER_INDIA_ANY',
	'Thank you, friend.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NEAR_INITIATOR_POSITIVE_LEADER_INDONESIA_ANY',
	'We knew you had it in you.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NEAR_INITIATOR_POSITIVE_LEADER_ISRAEL_ANY',
	'Good. This offer benefits both the Israeli and your people.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NEAR_INITIATOR_POSITIVE_LEADER_JAPAN_ANY',
	'It would be our honor.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NEAR_INITIATOR_POSITIVE_LEADER_MADAGASCAR_ANY',
	'Certainly. Madagascar thanks you.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NEAR_INITIATOR_POSITIVE_LEADER_MALAYSIA_ANY',
	'Yes, excellent.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NEAR_INITIATOR_POSITIVE_LEADER_MALI_ANY',
	'Sure. Prosperity blesses us both.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NEAR_INITIATOR_POSITIVE_LEADER_NETHERLANDS_ANY',
	'Yes. We express our gratitude.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NEAR_INITIATOR_POSITIVE_LEADER_PAKISTAN_ANY',
	'Much obliged.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NEAR_INITIATOR_POSITIVE_LEADER_PHILIPPINES_ANY',
	'It would be my pleasure.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NEAR_INITIATOR_POSITIVE_LEADER_POLAND_ANY',
	'Yes. We accept your generous proposal.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NEAR_INITIATOR_POSITIVE_LEADER_SOUTH_KOREA_ANY',
	'Absolutely. Thanks for the offer.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NEAR_INITIATOR_POSITIVE_LEADER_SWEDEN_ANY',
	'Yes. Sweden thanks you.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NEAR_INITIATOR_POSITIVE_LEADER_THAILAND_ANY',
	'Thank you for your hospitality. I only hope I will be able to reciprocate.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NEAR_INITIATOR_POSITIVE_LEADER_TURKEY_ANY',
	'Great is our charity! It will be done.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NEAR_INITIATOR_POSITIVE_LEADER_UK_ANY',
	'We find this agreeable. Thank you.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NEAR_INITIATOR_POSITIVE_LEADER_UKRAINE_ANY',
	'Yes, yes, my friend! We would love to.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NEAR_INITIATOR_POSITIVE_LEADER_VIETNAM_ANY',
	'Yes.'),
	
	-- AI invitation to exchange Capital Information (ANY)
	('en_US',	'LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_AMERICA_ANY',
	'We’d like to exchange information about our capitals; promote free trade between our nations, and all that.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_ARABIA_ANY',
	'Come, let us exchange information about our capitals. We invite you to tell me of your people, and we are happy to tell you of ours.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_AUSTRALIA_ANY',
	'We think an exchange of knowledge, the stories of our capitals perhaps, would be a great boon to our budding friendship.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_BRAZIL_ANY',
	'Would you like to trade information about our capitals? Brasília is a fine, modern city. What is yours like?'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_CANADA_ANY',
	'We would be honored to welcome representatives to learn about our capital. Grant us the same courtesy, if you will.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_COLOMBIA_ANY',
	'In the spirit of friendship, let us discover about our two different capitals.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_CUBA_ANY',
	'Our nations would both benefit if we were to exchange information about our capitals. What is your capital like?'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_EGYPT_ANY',
	'Shall we exchange information on our capitals? Ours is an ancient city, full of history and wonder. Tell us of yours.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_ETHIOPIA_ANY',
	'In the spirit of friendship, we will tell you of our home, if you will repay the favor.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_FRANCE_ANY',
	'Shall we exchange information about our capitals? Paris is a light to the world. What is your city like?'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_GREECE_ANY',
	'Athens is a glorious metropolis. What is your capital like? Come, let’s exchange information.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_ICELAND_ANY',
	'Our main settlement doesn’t have too much right now. But the hot springs are excellent! Anyway, what is your capital like?'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_INDIA_ANY',
	'Us Indians enjoy travel, perhaps we will one day visit your capital. Is it far? Would you tell us about it?'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_INDONESIA_ANY',
	'Where is your capital? We will share the location of our own, of course.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_ISRAEL_ANY',
	'Tell us of the location of your capital, that our maps might be complete. We shall share Jerusalem’s location in exchange.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_JAPAN_ANY',
	'We would like to exchange information about our capitals. Ours is Tokyo, the largest city in the world. What is yours like?'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_MADAGASCAR_ANY',
	'Antananarivo, the City of a Thousand, would fit very well on both of our maps, if you were to share the same favor to us as well.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_MALAYSIA_ANY',
	'Let us exchange information on our capital cities, and perhaps we can map out a prosperous trade route?'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_MALI_ANY',
	'Shall we fill the empty places on our maps with the locations of our mutual capitals?'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_MONGOLIA_ANY',
	'We should exchange information on our capitals. Someday we may want to visit you.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_NETHERLANDS_ANY',
	'The Netherlands welcomes you to learn of our capital, and invite you to reciprocate.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_NIGERIA_ANY',
	'As an act of goodwill, we should exchange information about our capitals. Don’t you agree?'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_PAKISTAN_ANY',
	'Do you want to share information about our capitals? Doing so would be advantageous to us both.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_PHILIPPINES_ANY',
	'It seems we have both travelled far; let us exchange information about our capitals. Please, tell us of your people and their ideals.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_POLAND_ANY',
	'Tell us of your capital. Of course, I am happy to tell you of Poland’s, if you wish.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_RUSSIA_ANY',
	'Would you like to exchange information of our capitals? Ours, Moscow, is a beacon of progress, but we do not know yours.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_SOUTH_KOREA_ANY',
	'South Korea will provide directions to our capital, should you reciprocate.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_SPAIN_ANY',
	'Would you like to hear of our capital? Madrid is the most beautiful of cities. Is your capital beautiful as well?'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_SWEDEN_ANY',
	'Sweden will inform your delegates of the location of our capital, Stockholm, but we expect that you will grant us the same favor.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_THAILAND_ANY',
	'Tell us about your capital, and we’ll tell you about ours, Bangkok. It’s only good diplomacy.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_TURKEY_ANY',
	'If you tell us of the location of your capital, we shall make a gift of Ankara’s location, as a sign of our generous intent.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_UK_ANY',
	'In the interest of our political relationship, we would like to know more about your capital... in exchange for information on ours, London, of course.'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_UKRAINE_ANY',
	'We’re sure your capital is filled with many people like the Ukrainians. Of course, where is your capital? Would you be willing to share that with us?'),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_VIETNAM_ANY',
	'Let us tell you of the citadels of Hanoi, and we will know yours in return.'),
	

-- Diplos | Delegation
	

	-- AI Accepts (ANY)
	('en_US',	'LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_AMERICA_ANY',
	'We welcome your delegation to the great United States of America.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_ARABIA_ANY',
	'A thousand thanks for your gifts. Your delegation will be treated with the utmost regard in Saudi Arabia.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_AUSTRALIA_ANY',
	'Australia has warmly welcomed the delegation you sent to visit our capital. We plan on meeting them personally to discuss our latest efforts.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_BRAZIL_ANY',
	'You have Brazil’s thanks. Our people are honored to have your delegation as a guest.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_CANADA_ANY',
	'Thank you for the kindness of your delegation. We are pleased to receive them.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_CHINA_PRC_ANY',
	'We are happy to welcome your trade delegation. They will be treated with the honor they deserve.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_CHINA_ROC_ANY',
	'We are happy to welcome your trade delegation. They will be treated with the honor they deserve.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_COLOMBIA_ANY',
	'We held a parade and a festival in the town square in your delegation’s honor. They had a long night. Let them sleep in.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_CUBA_ANY',
	'Very well. Your delegation will be treated warmly into Havana!'),
	('en_US',	'LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_ETHIOPIA_ANY',
	'When you talk to your delegation upon their return, they will tell you of the beauty of the Roof of Africa. Thank you.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_FRANCE_ANY',
	'We received your delegation at the French parliament. Thank you. The gifts will be treasured.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_GREECE_ANY',
	'The Greek people happily received your delegation and gifts. Thank you.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_INDIA_ANY',
	'You are too kind, our friend. Your gifts arrived with your trade delegation, and India has personally thanked them.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_INDONESIA_ANY',
	'Your delegation did not embarrass themselves. This speaks well of your people.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_IRELAND_ANY',
	'Your delegation has arrived into Dublin, and we showed them the finest hospitality. Thank you.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_ISRAEL_ANY',
	'Your delegation is welcome, and will find rest among the Israeli.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_ITALY_ANY',
	'Your trade delegation arrived, saw, and showed us their kindness. Thank you for the gifts.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_JAPAN_ANY',
	'Your delegation arrived, and we are humbled by your generosity.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_KAZAKHSTAN_ANY',
	'Your delegation arrived showing your generosity to Kazakhstan. It is greatly appreciated.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_MADAGASCAR_ANY',
	'You are very generous. The Malagasy are grateful for your gifts, and this will benefit us both.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_MALAYSIA_ANY',
	'We gladly accept. Your delegates are welcome to stay and enjoy their time in Malaysia.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_MALI_ANY',
	'The sincerity of your gift is its own blessing to Mali. We will accept your delegation.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_MEXICO_ANY',
	'Your delegation is welcome to Mexico. We thank you for the gifts they bring, and promise to treat them to the best we have to offer.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_NETHERLANDS_ANY',
	'We have welcomed your delegates with appropriate honors, and we thank you.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_NIGERIA_ANY',
	'We’re pleased to welcome your delegation to Nigeria. They will be treated with the best hospitality of our people.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_PAKISTAN_ANY',
	'Your delegation has arrived in Pakistan, and been welcomed with the proper formality. We thank you for the gifts they brought.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_PHILIPPINES_ANY',
	'Why, thank you. We are truly humbled by your generosity, and the Filipino peoples are grateful.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_PORTUGAL_ANY',
	'Your delegation was well received. The Portuguese are grateful for what you brought to us in Lisbon.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_SPAIN_ANY',
	'Spain has received your trade delegation. We will be sure to instruct them in our ways.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_SWEDEN_ANY',
	'We will accept your delegation, and they will stay as our honored guests to Sweden.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_THAILAND_ANY',
	'Your delegation has been gratefully received. They are resting in Bangkok and enjoying the hospitality.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_TURKEY_ANY',
	'We have received your delegation. Their gifts have been placed in the treasury with those of the others.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_UK_ANY',
	'We have received your trade delegation, and you may rest assured that we will treat them with the dignity they deserve.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_VIETNAM_ANY',
	'Your delegation has seen the beauty of Vietnam, and the fierceness of its people. Thank you for the gifts.'),
	
	-- AI Rejects (ANY)
	('en_US',	'LOC_DIPLO_REJECT_DELEGATION_FROM_HUMAN_LEADER_AMERICA_ANY',
	'We must decline.'),
	('en_US',	'LOC_DIPLO_REJECT_DELEGATION_FROM_HUMAN_LEADER_AUSTRALIA_ANY',
	'Australia respectfully declines your delegation.'),
	('en_US',	'LOC_DIPLO_REJECT_DELEGATION_FROM_HUMAN_LEADER_COLOMBIA_ANY',
	'Colombia won’t accept. Maybe some other time.'),
	('en_US',	'LOC_DIPLO_REJECT_DELEGATION_FROM_HUMAN_LEADER_CUBA_ANY',
	'Apologies, but we must refuse for the moment.'),
	('en_US',	'LOC_DIPLO_REJECT_DELEGATION_FROM_HUMAN_LEADER_ETHIOPIA_ANY',
	'We don’t need any.'),
	('en_US',	'LOC_DIPLO_REJECT_DELEGATION_FROM_HUMAN_LEADER_FRANCE_ANY',
	'Tempting, but no.'),
	('en_US',	'LOC_DIPLO_REJECT_DELEGATION_FROM_HUMAN_LEADER_INDONESIA_ANY',
	'Not right now. An ill tide rolls in — best our people do not associate it with yours.'),
	('en_US',	'LOC_DIPLO_REJECT_DELEGATION_FROM_HUMAN_LEADER_IRELAND_ANY',
	'We are sorry, but we’d rather not allow your people into Irish lands. Perhaps some other time.'),
	('en_US',	'LOC_DIPLO_REJECT_DELEGATION_FROM_HUMAN_LEADER_ITALY_ANY',
	'A good offer, but we cannot accept foreign gifts for the time being.'),
	('en_US',	'LOC_DIPLO_REJECT_DELEGATION_FROM_HUMAN_LEADER_JAPAN_ANY',
	'No, but thank you for the offer.'),
	('en_US',	'LOC_DIPLO_REJECT_DELEGATION_FROM_HUMAN_LEADER_MADAGASCAR_ANY',
	'Right now, we can’t accept any foreign gifts. We apologise.'),
	('en_US',	'LOC_DIPLO_REJECT_DELEGATION_FROM_HUMAN_LEADER_MALAYSIA_ANY',
	'I’m sorry, but we cannot allow that at this time.'),
	('en_US',	'LOC_DIPLO_REJECT_DELEGATION_FROM_HUMAN_LEADER_MEXICO_ANY',
	'Perhaps another time.'),
	('en_US',	'LOC_DIPLO_REJECT_DELEGATION_FROM_HUMAN_LEADER_NIGERIA_ANY',
	'A kind offer, but we must decline.'),
	('en_US',	'LOC_DIPLO_REJECT_DELEGATION_FROM_HUMAN_LEADER_PAKISTAN_ANY',
	'No, thank you.'),
	('en_US',	'LOC_DIPLO_REJECT_DELEGATION_FROM_HUMAN_LEADER_PHILIPPINES_ANY',
	'I’m afraid I cannot accept this.'),
	('en_US',	'LOC_DIPLO_REJECT_DELEGATION_FROM_HUMAN_LEADER_PORTUGAL_ANY',
	'You are sending gifts to an over-saturated market. We don’t want any.'),
	('en_US',	'LOC_DIPLO_REJECT_DELEGATION_FROM_HUMAN_LEADER_THAILAND_ANY',
	'No, thank you. Our people already have plenty, and to accept such gifts would be wasteful.'),
	('en_US',	'LOC_DIPLO_REJECT_DELEGATION_FROM_HUMAN_LEADER_UK_ANY',
	'Our Parliament does not approve.'),
	('en_US',	'LOC_DIPLO_REJECT_DELEGATION_FROM_HUMAN_LEADER_VIETNAM_ANY',
	'You say they come in peace, but we cannot allow any foreign infiltrators.'),
	
	-- AI Requests (ANY)
	('en_US',	'LOC_DIPLO_DELEGATION_FROM_AI_LEADER_AMERICA_ANY',
	'It’s good to see you. Our diplomatic delegation should be arriving soon with some fresh-baked apple pies. We’re sure you’ll give them a warm welcome.'),
	('en_US',	'LOC_DIPLO_DELEGATION_FROM_AI_LEADER_ARABIA_ANY',
	'I have decided to honor you with a delegation from my Kingdom. Please accept our generous gifts and chicken kabsa, as a mark of our respect.'),
	('en_US',	'LOC_DIPLO_DELEGATION_FROM_AI_LEADER_AUSTRALIA_ANY',
	'We’ve sent a trade delegation to your territories with a small selection of mince pies made across our cities. We hope you will receive them with our sincerest thanks.'),
	('en_US',	'LOC_DIPLO_DELEGATION_FROM_AI_LEADER_BRAZIL_ANY',
	'Brazil’s delegation comes with servings of brigadeiros and fejioada for you. I hope you welcome them in.'),
	('en_US',	'LOC_DIPLO_DELEGATION_FROM_AI_LEADER_COLOMBIA_ANY',
	'We send to you a delegation of our finest citizens carrying coffee and empanadas. Will you let them in?'),
	('en_US',	'LOC_DIPLO_DELEGATION_FROM_AI_LEADER_CUBA_ANY',
	'A delegation is on its way to your land! I’ve recommended they bring some Cuban cigars and ropa vieja to share with you.'),
	('en_US',	'LOC_DIPLO_DELEGATION_FROM_AI_LEADER_ETHIOPIA_ANY',
	'Ethiopia sends you coffee, injera bread, and our warm wishes.'),
	('en_US',	'LOC_DIPLO_DELEGATION_FROM_AI_LEADER_FRANCE_ANY',
	'We have sent you a trade delegation from France. They bring champagne, to toast our future friendship.'),
	('en_US',	'LOC_DIPLO_DELEGATION_FROM_AI_LEADER_INDIA_ANY',
	'India have sent a trade delegation to you with gifts from our land: teas, curries, and sitars. Please, enjoy.'),
	('en_US',	'LOC_DIPLO_DELEGATION_FROM_AI_LEADER_IRELAND_ANY',
	'We have sent a delegation to you, with some fine drink. Believe us, it’s the best whiskey you’ll have.'),
	('en_US',	'LOC_DIPLO_DELEGATION_FROM_AI_LEADER_MADAGASCAR_ANY',
	'Our Malagasy delegation has brought some lasary to eat and ranovola to drink. Will you let them bring it in?'),
	('en_US',	'LOC_DIPLO_DELEGATION_FROM_AI_LEADER_MALAYSIA_ANY',
	'We have sent a delegation with mangosteen, congee and the finest kuih dishes to express our gratitude for your kindness. I hope you enjoy them.'),
	('en_US',	'LOC_DIPLO_DELEGATION_FROM_AI_LEADER_NETHERLANDS_ANY',
	'The Netherlands send you gifts of greeting—wooden shoes, cheeses, and some delightful stroopwafels.'),
	('en_US',	'LOC_DIPLO_DELEGATION_FROM_AI_LEADER_NIGERIA_ANY',
	'Please accept Nigeria’s delegation into your lands. They bring jollof rice, aso oke cloths, and an offer of friendship.'),
	('en_US',	'LOC_DIPLO_DELEGATION_FROM_AI_LEADER_PAKISTAN_ANY',
	'The delegation of Pakistan sends you some paratha bread and samosas for you. Please welcome them graciously.'),
	('en_US',	'LOC_DIPLO_DELEGATION_FROM_AI_LEADER_PHILIPPINES_ANY',
	'We have sent a trade delegation with gifts, courtesy of the people of the Philippines: exquisite coffee beans, first-rate tobacco leaves, and the finest sugar you’ve ever tasted.'),
	('en_US',	'LOC_DIPLO_DELEGATION_FROM_AI_LEADER_PORTUGAL_ANY',
	'Portugal brings you spices from the Caribbean, silks from China, and gold from Africa. And a little bacalao from home.'),
	('en_US',	'LOC_DIPLO_DELEGATION_FROM_AI_LEADER_SOUTH_KOREA_ANY',
	'Please accept our world-known kimchi as part of our delegation. It comes with soy sauce, too.'),
	('en_US',	'LOC_DIPLO_DELEGATION_FROM_AI_LEADER_SPAIN_ANY',
	'We have sent a delegation to your city. Please, enjoy the churros and welcome them kindly.'),
	('en_US',	'LOC_DIPLO_DELEGATION_FROM_AI_LEADER_THAILAND_ANY',
	'A trade delegation should arrive shortly on behalf of the Thai people, with some fine pad thai. We hope you will accept with sincere thanks.'),
	('en_US',	'LOC_DIPLO_DELEGATION_FROM_AI_LEADER_UK_ANY',
	'Greetings. We have sent an envoy on behalf of the United Kingdom. We hope they are well received.'),
	('en_US',	'LOC_DIPLO_DELEGATION_FROM_AI_LEADER_VIETNAM_ANY',
	'Vietnam’s delegation is coming, with some delicious phở and gỏi cuốn. Will you let them in?'),
	
-- Diplos | Kudos and Warnings

	-- Random Agendas
	('en_US',	'LOC_DIPLO_KUDO_LEADER_AMERICA_REASON_AGENDA_SYCOPHANT_GOLDEN_AGE',
	'The people of America and every nation in the world look upon you with wonder. You are an inspiration to the world!'),
	('en_US',	'LOC_DIPLO_KUDO_LEADER_AUSTRALIA_REASON_AGENDA_SYCOPHANT_GOLDEN_AGE',
	'We are glad to see that your civilization prospers under your leadership, with a golden age. Well done!'),
	('en_US',	'LOC_DIPLO_KUDO_LEADER_BRAZIL_REASON_AGENDA_SYCOPHANT_GOLDEN_AGE',
	'We look upon your nation and its works, and we understand why your people are praised in song and story around the world.'),
	('en_US',	'LOC_DIPLO_KUDO_LEADER_CHINA_PRC_REASON_AGENDA_SYCOPHANT_GOLDEN_AGE',
	'Your personal magnificence is reflected in the glory of your nation!'),
	('en_US',	'LOC_DIPLO_KUDO_LEADER_IRAN_REASON_AGENDA_SYCOPHANT_GOLDEN_AGE',
	'Allah has truly blessed your civilization with the inspirational golden age you achieved.'),
	('en_US',	'LOC_DIPLO_KUDO_LEADER_RUSSIA_REASON_AGENDA_SYCOPHANT_GOLDEN_AGE',
	'Your nation is the model on which we will build the new Russia!'),
	('en_US',	'LOC_DIPLO_KUDO_LEADER_SPAIN_REASON_AGENDA_SYCOPHANT_GOLDEN_AGE',
	'What could be better than to surround oneself with such musicians, saints and scientists? We have always thought that a great nation is a manifestation of the blessings of the Almighty.'),
	('en_US',	'LOC_DIPLO_KUDO_LEADER_AMERICA_REASON_AGENDA_SYMPATHIZER_DARK_AGE',
	'Don’t worry about the dark age your peoples are facing. Things may be bad now, but they will get better.'),
	('en_US',	'LOC_DIPLO_KUDO_LEADER_CANADA_REASON_AGENDA_SYMPATHIZER_DARK_AGE',
	'We are sorry to see your current misfortunes. If there is anything we can do to help, let Canada know.'),
	('en_US',	'LOC_DIPLO_KUDO_LEADER_FRANCE_REASON_AGENDA_SYMPATHIZER_DARK_AGE',
	'We are sending you a gift: A ring inscribed with “Ceci Aussi Devrait Passer”. This too shall pass. May it comfort you in times of trouble.'),
	('en_US',	'LOC_DIPLO_KUDO_LEADER_IRAN_REASON_AGENDA_SYMPATHIZER_DARK_AGE',
	'Pray to Allah, and he will see you through these dark times. We’re here for you.'),
	('en_US',	'LOC_DIPLO_KUDO_LEADER_MONGOLIA_REASON_AGENDA_SYMPATHIZER_DARK_AGE',
	'We admire the way you rule. We do appreciate not having to come up with a complicated strategy to conquer your nation.'),
	('en_US',	'LOC_DIPLO_KUDO_LEADER_POLAND_REASON_AGENDA_SYMPATHIZER_DARK_AGE',
	'Your heart must ache for the suffering of your people. Poland understands your plight, and we pray for you.'),
	('en_US',	'LOC_DIPLO_KUDO_LEADER_RUSSIA_REASON_AGENDA_SYMPATHIZER_DARK_AGE',
	'A lesser leader would be unable to do what you are doing: Keeping firm control of your nation in a time of crisis.'),
	('en_US',	'LOC_DIPLO_KUDO_LEADER_SOUTH_AFRICA_REASON_AGENDA_SYMPATHIZER_DARK_AGE',
	'While things may look bleak at the moment, know that you have the strength within you to overcome any challenge.'),
	('en_US',	'LOC_DIPLO_KUDO_LEADER_THAILAND_REASON_AGENDA_SYMPATHIZER_DARK_AGE',
	'Thailand feels for your people. We pray unceasingly that you will soon be liberated, and at peace.'),
	('en_US',	'LOC_DIPLO_KUDO_LEADER_UK_REASON_AGENDA_SYMPATHIZER_DARK_AGE',
	'You bear the suffering of your Dark Age with such nobility! We wish our citizens were as stalwart as you!'),


-- Diplos | Open Borders
	

	-- AI accepts from human (ANY)	
	('en_US',	'LOC_DIPLO_ACCEPT_OPEN_BORDERS_FROM_HUMAN_LEADER_FRANCE_ANY',
	'Oh, very well. You may pass.'),
	('en_US',	'LOC_DIPLO_ACCEPT_OPEN_BORDERS_FROM_HUMAN_LEADER_JAPAN_ANY',
	'Your people may pass through our borders, but they must honor our ways.'),
	('en_US',	'LOC_DIPLO_ACCEPT_OPEN_BORDERS_FROM_HUMAN_LEADER_VIETNAM_ANY',
	'Your people may pass, but they will be watched.'),
	
	-- AI rejects from human (ANY)	
	('en_US',	'LOC_DIPLO_REJECT_OPEN_BORDERS_FROM_HUMAN_LEADER_FRANCE_ANY',
	'Unfortunately, I simply cannot allow it. For safety, of course.'),
	('en_US',	'LOC_DIPLO_REJECT_OPEN_BORDERS_FROM_HUMAN_LEADER_GERMANY_ANY',
	'I was not born a fool, to allow my enemies passage through my lands.'),
	('en_US',	'LOC_DIPLO_REJECT_OPEN_BORDERS_FROM_HUMAN_LEADER_JAPAN_ANY',
	'The Land of the Rising Sun is denied to you. Ask yourself “why?”'),
	('en_US',	'LOC_DIPLO_REJECT_OPEN_BORDERS_FROM_HUMAN_LEADER_VIETNAM_ANY',
	'Vietnam did not live for this long just to allow foreign troops to march across our soil. No.'),
	
	-- AI requests from human (ANY)	
	('en_US',	'LOC_DIPLO_OPEN_BORDERS_FROM_AI_LEADER_VIETNAM_ANY',
	'Will you permit our people passage? We need to see some new lands.'),
	

-- Diplos | Declare Friendship
	

	-- AI accepts from human (ANY)
	('en_US',	'LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_HUMAN_LEADER_ARABIA_ANY',
	'We understand now that you are a friend to Saudi Arabia. Let us declare our friendship to the world.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_HUMAN_LEADER_AMERICA_ANY',
	'We can’t say no to that. Thank you for your generous offer, and may we work together in unity!'),
	('en_US',	'LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_HUMAN_LEADER_ARGENTINA_ANY',
	'We accept your offer of friendship. Together, we can work towards a brighter future.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_HUMAN_LEADER_AUSTRALIA_ANY',
	'We would gladly recognize the strong friendship between our nations.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_HUMAN_LEADER_CHINA_PRC_ANY',
	'You have proven yourself a worthy friend to China. We accept your offer.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_HUMAN_LEADER_CONGO_ANY',
	'On behalf of the people of DR Congo, we accept your friendship and good will.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_HUMAN_LEADER_CUBA_ANY',
	'Of course we can be friends! A friend to Cuba is a friend to unity.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_HUMAN_LEADER_ETHIOPIA_ANY',
	'Together, our people will grow strong under the light of God.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_HUMAN_LEADER_GERMANY_ANY',
	'A strong ally is the greatest friend. Let us live in peace.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_HUMAN_LEADER_GREECE_ANY',
	'On the behalf of the Greeks, we accept your friendship.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_HUMAN_LEADER_INDIA_ANY',
	'We accept your offer of friendship. May it be blessed with peace.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_HUMAN_LEADER_INDONESIA_ANY',
	'A fortunate coincidence — I was about to ask the same. Good! The matter is settled.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_HUMAN_LEADER_IRELAND_ANY',
	'Definitely. Let the world know that we stand together.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_HUMAN_LEADER_ISRAEL_ANY',
	'When two great peoples such as ours share such an accord, it is right to call them friends.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_HUMAN_LEADER_ITALY_ANY',
	'Let it be known that your country is a friend to Italy, and that we are joined together in friendship.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_HUMAN_LEADER_JAPAN_ANY',
	'We see in you the peace and tranquility of a warrior, and we welcome that friendship.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_HUMAN_LEADER_MALAYSIA_ANY',
	'The pleasure would be mine. Thank you, and may we both prosper.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_HUMAN_LEADER_NETHERLANDS_ANY',
	'We are greatly pleased to accept the hand of friendship. May our future be long and prosperous!'),
	('en_US',	'LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_HUMAN_LEADER_NIGERIA_ANY',
	'There is strength in numbers. We gladly accept your friendship.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_HUMAN_LEADER_PAKISTAN_ANY',
	'We are glad to call you friend. In this dangerous world, friends are a scarce and valuable thing.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_HUMAN_LEADER_PHILIPPINES_ANY',
	'I would be very much happy to welcome your friendship to the Philippines.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_HUMAN_LEADER_POLAND_ANY',
	'Of course we will accept your friendship. You are a shining example of goodness in this world.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_HUMAN_LEADER_RUSSIA_ANY',
	'Your offer is kind. We accept, for the good of our people and yours.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_HUMAN_LEADER_SOUTH_KOREA_ANY',
	'We will gladly be friends. Friendship is the foundation of peace.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_HUMAN_LEADER_THAILAND_ANY',
	'I gladly accept, on behalf of my people. Thank you.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_HUMAN_LEADER_UK_ANY',
	'Yes, this pleases us. Our two nations will surely benefit from our friendship.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_HUMAN_LEADER_VIETNAM_ANY',
	'Of course. Vietnam knows your qualities, so, let’s live in peace together.'),
	
	-- AI rejects from human (ANY)	
	('en_US',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_HUMAN_LEADER_ARABIA_ANY',
	'Your offer is a generous and kind one, but we must humbly decline until we can be assured of your intentions.'),
	('en_US',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_HUMAN_LEADER_ARGENTINA_ANY',
	'Argentina is not interested at this time.'),
	('en_US',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_HUMAN_LEADER_AUSTRALIA_ANY',
	'We hope you’ll understand, Australia just can’t commit to any official gestures at this time.'),
	('en_US',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_HUMAN_LEADER_CHINA_PRC_ANY',
	'You are not yet worthy of our friendship.'),
	('en_US',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_HUMAN_LEADER_CONGO_ANY',
	'DR Congo is not ready to accept your friendship. Let our relationship ripen first.'),
	('en_US',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_HUMAN_LEADER_CUBA_ANY',
	'This isn’t an offer we can accept at the time being.'),
	('en_US',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_HUMAN_LEADER_ETHIOPIA_ANY',
	'Forgive me. Ethiopia has not been free for so long by making hasty agreements with foreigners.'),
	('en_US',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_HUMAN_LEADER_FRANCE_ANY',
	'We apologize, but this would be too sudden a change. Perhaps another time?'),
	('en_US',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_HUMAN_LEADER_GERMANY_ANY',
	'No, we cannot accept your friendship, for the good of Germany.'),
	('en_US',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_HUMAN_LEADER_GREECE_ANY',
	'No, we will not be friends until you can prove it by deed, or convince us otherwise.'),
	('en_US',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_HUMAN_LEADER_INDIA_ANY',
	'I am sorry, but India cannot enter into this agreement with you. Please understand, it is only for the best.'),
	('en_US',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_HUMAN_LEADER_INDONESIA_ANY',
	'I would not go so far as to call you a friend. Until I know your true motives, we must remain as we are.'),
	('en_US',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_HUMAN_LEADER_IRELAND_ANY',
	'I’m sorry, but we simply must decline for now.'),
	('en_US',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_HUMAN_LEADER_ISRAEL_ANY',
	'You flatter yourself. Israel recognizes the existence of your nation—but we do not recognize a mutual friendship.'),
	('en_US',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_HUMAN_LEADER_ITALY_ANY',
	'Italy must remain Italy: a friend to no one more than to herself.'),
	('en_US',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_HUMAN_LEADER_KAZAKHSTAN_ANY',
	'Our friendship is not given lightly. You must earn Kazakhstan’s trust, first.'),
	('en_US',	'LOC_DIPLO_REJ ECT_DECLARE_FRIEND_FROM_HUMAN_LEADER_MALAYSIA_ANY',
	'I see no friend in you, for now. Maybe later on, when we know your qualities.'),
	('en_US',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_HUMAN_LEADER_NETHERLANDS_ANY',
	'We do not recognize your claim of friendship with the Netherlands.'),
	('en_US',	'LOC_DIPLO_REJ ECT_DECLARE_FRIEND_FROM_HUMAN_LEADER_NIGERIA_ANY',
	'We do not need your friendship at this time. Maybe later.'),
	('en_US',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_HUMAN_LEADER_PAKISTAN_ANY',
	'Unfortunately, we do not have the confidence in you to call you friend.'),
	('en_US',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_HUMAN_LEADER_PHILIPPINES_ANY',
	'We cannot, for the good of the Filipino people.'),
	('en_US',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_HUMAN_LEADER_POLAND_ANY',
	'We humbly decline your offer of friendship. It is not God’s will at this time.'),
	('en_US',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_HUMAN_LEADER_RUSSIA_ANY',
	'Russia must decline. An old friend is better than two new ones.'),
	('en_US',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_HUMAN_LEADER_SOUTH_KOREA_ANY',
	'South Korea isn’t willing enough to tell the world we are friends just yet.'),
	('en_US',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_HUMAN_LEADER_THAILAND_ANY',
	'I don’t believe this is the right time for us to make such a declaration.'),
	('en_US',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_HUMAN_LEADER_UK_ANY',
	'It is too early to make such a commitment. We will reconsider when appropriate, naturally. You do understand?'),
	('en_US',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_HUMAN_LEADER_VIETNAM_ANY',
	'Vietnam stands alone. We do not need you.'),
	
	-- AI Requests friendship from human (ANY)	
	('en_US',	'LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_AMERICA_ANY',
	'You have earned the United States of America’s respect. Shall we declare our friendship?'),
	('en_US',	'LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_ARABIA_ANY',
	'You have proven yourself a wise and just leader. Would you accept Saudi Arabia’s offer of friendship?'),
	('en_US',	'LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_ARGENTINA_ANY',
	'Solving problems requires teamwork. Can we work together, as friends?'),
	('en_US',	'LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_AUSTRALIA_ANY',
	'We believe our friendship is built on a mutual interest in maintaining stability and protecting those in need. We hope you agree.'),
	('en_US',	'LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_CHINA_PRC_ANY',
	'Please, allow us to return your friendship with ours.'),
	('en_US',	'LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_COLOMBIA_ANY',
	'We both lead the roles of goodness in the world. Will you accept Colombia’s friendship?'),
	('en_US',	'LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_CONGO_ANY',
	'We extend our hand in friendship to you. Let our people be brothers and sisters under the Lord.'),
	('en_US',	'LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_CUBA_ANY',
	'Would you be willing to sign a declaration of friendship between Cuba and your great nation?'),
	('en_US',	'LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_ETHIOPIA_ANY',
	'We offer you the friendship of the line of Solomon, and the Lion of Judah! What do you say?'),
	('en_US',	'LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_FRANCE_ANY',
	'We extend to you France’s hand in friendship. Will you accept it?'),
	('en_US',	'LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_GERMANY_ANY',
	'Again, we extend our hand, but this time in friendship. Will you accept Germany’s friendship?'),
	('en_US',	'LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_GREECE_ANY',
	'Let’s put our differences aside for a moment, shall we? Friendship is more important - do you accept?'),
	('en_US',	'LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_ICELAND_ANY',
	'The world can be quite harsh to civilizations. Let us declare our friendship to the world!'),
	('en_US',	'LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_INDIA_ANY',
	'I suppose leadership at one time meant violence; but today it means getting along with people. So... will you accept India’s friendship?'),
	('en_US',	'LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_INDONESIA_ANY',
	'My people find yours a pleasure to encounter. If you feel the same of Indonesia, let us declare it to the world!'),
	('en_US',	'LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_IRELAND_ANY',
	'You’ve proven yourself a true friend of Ireland, her people, and her faith. I would ask you to stand with us as a friend!'),
	('en_US',	'LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_ISRAEL_ANY',
	'Come, gracious one, and declare to the world that you stand as Israel’s friend!'),
	('en_US',	'LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_ITALY_ANY',
	'Italy extends an offer of friendship, for the better of our great countries. Do you accept?'),
	('en_US',	'LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_JAPAN_ANY',
	'You are harmonious and wise. We offer you loyalty and honor, if you would accept us as your friend.'),
	('en_US',	'LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_KAZAKHSTAN_ANY',
	'Friendship is the most valuable thing between nations. Let us have it.'),
	('en_US',	'LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_MADAGASCAR_ANY',
	'We think of you as a kind, generous leader to Madagascar. We’d recognise a budding friendship between our peoples, if you agree.'),
	('en_US',	'LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_MALAYSIA_ANY',
	'You are a gifted ruler who knows the value of good relations. We formally extend to you Malaysia’s hand in friendship.'),
	('en_US',	'LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_NETHERLANDS_ANY',
	'Civilizations with such friendly relations as ours should proclaim this to the world, wouldn’t you agree?'),
	('en_US',	'LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_NIGERIA_ANY',
	'We extend our hand in friendship, to show the world that we are united as one. Do you accept Nigeria’s friendship?'),
	('en_US',	'LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_NORWAY_ANY',
	'We have never met someone as great as Norway, until we met you. Let us be friends, then.'),
	('en_US',	'LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_PAKISTAN_ANY',
	'We offer you our friendship, the highest honor we can give. What do you say?'),
	('en_US',	'LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_PHILIPPINES_ANY',
	'You demonstrate qualities of a great and noble leader. We offer you our hand in friendship.'),
	('en_US',	'LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_POLAND_ANY',
	'Your nation is as a sister to ours. Let us officially declare our friendship.'),
	('en_US',	'LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_RUSSIA_ANY',
	'We are honored to extend to you our friendship, and a friendship between our nations. Do you accept?'),
	('en_US',	'LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_SOUTH_KOREA_ANY',
	'Would you accept our friendship? Steadfast friends benefit the security of all.'),
	('en_US',	'LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_THAILAND_ANY',
	'You are a wise ruler who cares for their people. Thailand is honored to extend to you a hand in friendship.'),
	('en_US',	'LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_UK_ANY',
	'We are pleased to consider you an esteemed friend. We hope the feeling is mutual...'),
	('en_US',	'LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_VIETNAM_ANY',
	'Let our people share each other’s burdens, and the struggle will be easier. Will you become Vietnam’s friend?'),
	
	-- Human accepts AI requests, AI responds (ANY)	
	('en_US',	'LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_AI_LEADER_ARGENTINA_ANY',
	'Thank you very much.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_AI_LEADER_AUSTRALIA_ANY',
	'We appreciate everything you’ve done.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_AI_LEADER_COLOMBIA_ANY',
	'Excellent. You made the right choice.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_AI_LEADER_CUBA_ANY',
	'Excellent! Let us prosper.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_AI_LEADER_ETHIOPIA_ANY',
	'You are on the right side of history.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_AI_LEADER_ICELAND_ANY',
	'Good, good.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_AI_LEADER_INDONESIA_ANY',
	'Good, good.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_AI_LEADER_IRELAND_ANY',
	'Excellent.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_AI_LEADER_ISRAEL_ANY',
	'Yes. This we swear.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_AI_LEADER_MALAYSIA_ANY',
	'May this become the start of something wonderful.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_AI_LEADER_NETHERLANDS_ANY',
	'Wonderful.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_AI_LEADER_NIGERIA_ANY',
	'Thank you.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_AI_LEADER_PAKISTANI_ANY',
	'Correct choice, friend.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_AI_LEADER_PHILIPPINES_ANY',
	'Thank you, friend.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_AI_LEADER_POLAND_ANY',
	'Very good.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_AI_LEADER_THAILAND_ANY',
	'Excellent, both our peoples will be happier for it!'),
	('en_US',	'LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_AI_LEADER_UK_ANY',
	'You’ve been most kind and attentive.'),
	('en_US',	'LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_AI_LEADER_VIETNAM_ANY',
	'Wonderful.'),
	
	-- Human rejects AI requests, AI responds (ANY)	
	('en_US',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_AI_LEADER_AMERICA_ANY',
	'Oh, well. Perhaps next time, then.'),
	('en_US',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_AI_LEADER_ARABIA_ANY',
	'Well, mind what you say.'),
	('en_US',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_AI_LEADER_ARGENTINA_ANY',
	'That is too bad.'),
	('en_US',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_AI_LEADER_AUSTRALIA_ANY',
	'An unwelcome turn.'),
	('en_US',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_AI_LEADER_CHINA_PRC_ANY',
	'Bad luck...'),
	('en_US',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_AI_LEADER_COLOMBIA_ANY',
	'We extend our hand to you, and you slap it away. Disappointing.'),
	('en_US',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_AI_LEADER_CUBA_ANY',
	'How disappointing. Perhaps another time, then?'),
	('en_US',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_AI_LEADER_ETHIOPIA_ANY',
	'You are on the wrong side of history.'),
	('en_US',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_AI_LEADER_INDIA_ANY',
	'An unfortunate turn.'),
	('en_US',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_AI_LEADER_INDONESIA_ANY',
	'Are you trying to insult Indonesia?'),
	('en_US',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_AI_LEADER_IRELAND_ANY',
	'Quite a shame.'),
	('en_US',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_AI_LEADER_ISRAEL_ANY',
	'We do not consent to this.'),
	('en_US',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_AI_LEADER_JAPAN_ANY',
	'A shame...'),
	('en_US',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_AI_LEADER_KAZAKHSTAN_ANY',
	'You should reconsider.'),
	('en_US',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_AI_LEADER_MADAGASCAR_ANY',
	'That’s a bit sad.'),
	('en_US',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_AI_LEADER_MALAYSIA_ANY',
	'That is a pity.'),
	('en_US',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_AI_LEADER_NETHERLANDS_ANY',
	'How unfortunate.'),
	('en_US',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_AI_LEADER_NIGERIA_ANY',
	'Too bad.'),
	('en_US',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_AI_LEADER_PAKISTAN_ANY',
	'Regretful.'),
	('en_US',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_AI_LEADER_PHILIPPINES_ANY',
	'This is not what we hoped for.'),
	('en_US',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_AI_LEADER_POLAND_ANY',
	'I will ignore this insult.'),
	('en_US',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_AI_LEADER_PORTUGAL_ANY',
	'You make us sad.'),
	('en_US',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_AI_LEADER_THAILAND_ANY',
	'Unfortunate. But we’re certain you have your reasons.'),
	('en_US',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_AI_LEADER_VIETNAM_ANY',
	'You know what happens to our enemies, right?'),


-- Diplos | Alliance
	

	-- AI Requests an alliance from human (ANY)
	('en_US',	'LOC_DIPLO_MAKE_ALLIANCE_FROM_AI_LEADER_JAPAN_ANY',
	'You have been a friend to Japan. We would be honored if you would join us in an alliance.'),
	('en_US',	'LOC_DIPLO_MAKE_ALLIANCE_FROM_AI_LEADER_THAILAND_ANY',
	'Let us work together, to make the world a happier and more prosperous place. Please, join us in an alliance.'),
	('en_US',	'LOC_DIPLO_MAKE_ALLIANCE_FROM_AI_LEADER_VIETNAM_ANY',
	'Bring your troops alongside Vietnam’s! What say you?'),


-- Diplos | Troops Near Border
	
	('en_US',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_AMERICA_ANY',
	'You march your troops so close to our borders that the Americans are beginning to question your integrity.'),
	('en_US',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_ARABIA_ANY',
	'We would be blind to not see your army in front of us. Please, move them from our borders, unless… you anticipate war?'),
	('en_US',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_AUSTRALIA_ANY',
	'You can imagine how the mustering of your forces along our borders must look? We’re assuming it’s some sort of mistake.'),
	('en_US',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_CANADA_ANY',
	'The coureurs de bois bring us disturbing tidings of many troops along our borders. Perhaps you could withdraw them?'),
	('en_US',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_CHINA_PRC_ANY',
	'I see your troops are amassing near Chinese borders. This is unacceptable. Move them.'),
	('en_US',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_CHINA_ROC_ANY',
	'Your army has relinquished any advantage of surprise. Withdraw your forces, and rethink your strategy.'),
	('en_US',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_CONGO_ANY',
	'Your army is at our doorstep. Do you think we are blind? Move them, or Congo will be forced to action.'),
	('en_US',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_CUBA_ANY',
	'Do you think the Cubans are not wary of your troops on our borders? We demand you move them right away!'),
	('en_US',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_EGYPT_ANY',
	'Did you think we would not notice your army at Egyptian borders? We’d suggest you move them.'),
	('en_US',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_ETHIOPIA_ANY',
	'Do you think you can frighten Ethiopia? Move your troops at once!'),
	('en_US',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_FRANCE_ANY',
	'Do you think to intimidate us with force? That will not go well for you, at all.'),
	('en_US',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_GERMANY_ANY',
	'If you think we are blind to your army, you are naïve. Move them away from Germany, or suffer the consequences.'),
	('en_US',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_GREECE_ANY',
	'If you are trying to intimidate the Greeks with your army, it’s not working. Move them, or face the consequences.'),
	('en_US',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_ICELAND_ANY',
	'You do realise the only ones intimidated by that army are our livestock, right? Move your army away from Iceland right now, or face the consequences!'),
	('en_US',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_INDIA_ANY',
	'Do you intend to threaten the peace and harmony of India? Please, move your army away from our borders.'),
	('en_US',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_INDONESIA_ANY',
	'Why do your troops march near our the borders of Indonesia? The calm waters, once disturbed, can grow into a mighty typhoon.'),
	('en_US',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_IRAQ_ANY',
	'You test our patience with soldiers along Iraqi borders. Remove them or they shall be removed.'),
	('en_US',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_IRELAND_ANY',
	'Your troops are far too close to Irish borders. We do not wish to have to act against them, but this is unnerving the entire nation.'),
	('en_US',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_ISRAEL_ANY',
	'What treachery do you intend? Move your armies away from the borders of Israel at once.'),
	('en_US',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_ITALY_ANY',
	'Your soldiers are only a few steps from being invaders. Move them from the borders of Italy at once!'),
	('en_US',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_JAPAN_ANY',
	'Do not show your blade unless you mean to strike. Move your soldiers from our lands.'),
	('en_US',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_KAZAKHSTAN_ANY',
	'Your troops tread too close to Kazakh borders. We hope it’s just to view our picturesque countryside, or else, we’ll attack you.'),
	('en_US',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_MALI_ANY',
	'We see no need for you to parade your great armies at the borders of Mali. Please remove them now.'),
	('en_US',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_MEXICO_ANY',
	'Your troops threaten our borders. Know that Mexico will protect its sovereignty - please move them.'),
	('en_US',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_MONGOLIA_ANY',
	'The armies you have near our borders are a tempting target. For their safety, you should move them.'),
	('en_US',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_MOROCCO_ANY',
	'We hope your armies are on the borders of Morocco for purposes beyond intimidating us. Remove them now.'),
	('en_US',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_NETHERLANDS_ANY',
	'Do you think the Dutch are unaware of your plans? We demand you move your troops from our borders at once!'),
	('en_US',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_NEW_ZEALAND_ANY',
	'Maybe you want to move all those armies near New Zealander land? Before something terrible happens? Just a thought.'),
	('en_US',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_NIGERIA_ANY',
	'We see your soldiers camped at Nigerian borders. It would be wise of you to move them elsewhere.'),
	('en_US',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_NORTH_KOREA_ANY',
	'We see your soldiers. Send them away, before North Korea teaches them a lesson.'),
	('en_US',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_PAKISTAN_ANY',
	'Your soldiers stalk Pakistani borders. We hope you do not plan to add to the chaos of this world - move them.'),
	('en_US',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_POLAND_ANY',
	'Your armies have not gone unnoticed. Please remove them from our presence.'),
	('en_US',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_PORTUGAL_ANY',
	'Please, move your troops unless something calamitous might happen to the Portuguese.'),
	('en_US',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_RUSSIA_ANY',
	'Your military threatens Russia’s very borders... do you expect us to sit here and do nothing?'),
	('en_US',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_SOUTH_AFRICA_ANY',
	'Why do your troops stand near our borders? Is this some sort of threat to the South Africans?'),
	('en_US',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_SOUTH_KOREA_ANY',
	'Your soldiers infringe upon our border. I hope you do not intend to visit the horrors of war upon the world.'),
	('en_US',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_SPAIN_ANY',
	'Do not presume you can keep your soldiers on Spanish borders without repercussions. Move them at once.'),
	('en_US',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_SWEDEN_ANY',
	'Do not march your units up and down along our border like a child playing with toy soldiers. Move them now.'),
	('en_US',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_THAILAND_ANY',
	'The Thai people are scared for their lives all because of your troops. Move them immediately!'),
	('en_US',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_TURKEY_ANY',
	'Do not make martial displays on our border, for it risks angering us. Already many within Turkey are offended on our behalf.'),
	('en_US',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_UK_ANY',
	'Your army is not welcome at our borders. Remove them at once.'),
	('en_US',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_VIETNAM_ANY',
	'Vietnam will not be threatened. Move your troops.'),
	
	-- AI accepts player's warning for border troops warning
	('en_US',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_AI_RESPONSE_POSITIVE_LEADER_ETHIOPIA_ANY',
	'Friends do not need armed troops on each other’s borders. We will withdraw.'),
	('en_US',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_AI_RESPONSE_POSITIVE_LEADER_PORTUGAL_ANY',
	'Agreed. Our troops will travel elsewhere.'),
	('en_US',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_AI_RESPONSE_POSITIVE_LEADER_VIETNAM_ANY',
	'Our troops are mighty, and their cries terrible. We did not mean to frighten you.'),
	
	-- AI rejects player's warning for border troops warning (ANY) ~ DECLARES WAR
	('en_US',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_AI_RESPONSE_NEGATIVE_LEADER_ETHIOPIA_ANY',
	'My forces are where they are for good reason. War is coming.'),
	('en_US',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_AI_RESPONSE_NEGATIVE_LEADER_PORTUGAL_ANY',
	'We are sorry, but our plans necessitate placing our troops where they are.'),
	('en_US',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_AI_RESPONSE_NEGATIVE_LEADER_VIETNAM_ANY',
	'I do not have to listen to you. Get ready, war is upon you.'),


-- Diplos | Settling Too Close
	
	-- AI warns player for settling too close
	('en_US',	'LOC_DIPLO_WARNING_DONT_SETTLE_NEAR_ME_AI_LEADER_AMERICA_ANY',
	'Your territory is encroaching upon the sovereign lands of the United States. You have been warned for the last time.'),
	('en_US',	'LOC_DIPLO_WARNING_DONT_SETTLE_NEAR_ME_AI_LEADER_ARABIA_ANY',
	'You dare insult Allah and Saudi Arabia’s land by settling near it? Please settle elsewhere, or you will know your place.'),
	('en_US',	'LOC_DIPLO_WARNING_DONT_SETTLE_NEAR_ME_AI_LEADER_CHINA_ANY',
	'The People’s Republic of China is a prosperous nation, but we do not welcome your uninvited presence. Cease your expansion near our borders immediately.'),
	('en_US',	'LOC_DIPLO_WARNING_DONT_SETTLE_NEAR_ME_AI_LEADER_FRANCE_ANY',
	'Trying to grab some territory while the French were not looking? Continue and we guarantee you shall pay a heavy price.'),
	('en_US',	'LOC_DIPLO_WARNING_DONT_SETTLE_NEAR_ME_AI_LEADER_GERMANY_ANY',
	'We are a proud and mighty nation. Do not be a fool and insult Germany by settling lands which rightfully belong to her.'),
	('en_US',	'LOC_DIPLO_WARNING_DONT_SETTLE_NEAR_ME_AI_LEADER_INDIA_ANY',
	'The people of India cry out as you claim her lands. Please do not divide us through this reckless behavior.'),
	('en_US',	'LOC_DIPLO_WARNING_DONT_SETTLE_NEAR_ME_AI_LEADER_JAPAN_ANY',
	'It is not becoming of a great and powerful leader such as yourself to so brazenly claim whatever lands you please. We have no choice but to demand you reverse this pattern.'),
	('en_US',	'LOC_DIPLO_WARNING_DONT_SETTLE_NEAR_ME_AI_LEADER_RUSSIA_ANY',
	'Russia is very protective of her lands, and your settling near her constitutes a direct challenge. Do not continue with this behavior.'),
	('en_US',	'LOC_DIPLO_WARNING_DONT_SETTLE_NEAR_ME_AI_LEADER_THAILAND_ANY',
	'We had sincerely hoped that Thailand and your country might be wonderful friends. But if you keep constructing new settlements near us, we fear we will become enemies.'),
	('en_US',	'LOC_DIPLO_WARNING_DONT_SETTLE_NEAR_ME_AI_LEADER_TURKEY_ANY',
	'Come now, now, what do you think you’re doing expanding so close to Turkey? Stop that immediately.'),
	('en_US',	'LOC_DIPLO_WARNING_DONT_SETTLE_NEAR_ME_AI_LEADER_UK_ANY',
	'If you wish to join the United Kingdom, we welcome you. Discontinue, however, trying to take the lands which rightfully belong to us. Understood?'),
	('en_US',	'LOC_DIPLO_WARNING_DONT_SETTLE_NEAR_ME_AI_LEADER_VIETNAM_ANY',
	'Vietnam watches you. We cannot promise that our people will tolerate settling so close.'),
	
	-- Positive AI response to human request
	('en_US',	'LOC_DIPLO_WARNING_DONT_SETTLE_NEAR_ME_AI_RESPONSE_POSITIVE_LEADER_VIETNAM_ANY',
	'We were unaware that you laid claim to such lands. Rest assured, Vietnam shall find other, better lands to build upon elsewhere.'),
	
	-- Negative AI response to human request (HAPPY)
	('en_US',	'LOC_DIPLO_WARNING_DONT_SETTLE_NEAR_ME_AI_RESPONSE_NEGATIVE_LEADER_VIETNAM_HAPPY',
	'Our apologies, but we really need this land to thrive. There’s more land somewhere else for you.'),
	
	-- Negative AI response to human request (UNHAPPY)
	('en_US',	'LOC_DIPLO_WARNING_DONT_SETTLE_NEAR_ME_AI_RESPONSE_NEGATIVE_LEADER_VIETNAM_UNHAPPY',
	'This is Vietnam’s land by birthright. We will not be swayed to change locations.'),
	

-- Diplos | Trade
	

	-- AI Accepts Deal (HAPPY)
	('en_US',	'LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_AUSTRALIA_HAPPY',
	'Then we’re agreed!'),
	('en_US',	'LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_CANADA_HAPPY',
	'We accept your proposal, with thanks.'),
	('en_US',	'LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_INDONESIA_HAPPY',
	'Yes, good.'),
	('en_US',	'LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_MALAYSIA_HAPPY',
	'Excellent.'),
	('en_US',	'LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_MALI_HAPPY',
	'This we shall except.'),
	('en_US',	'LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_NETHERLANDS_HAPPY',
	'We have heard no better offer.'),
	('en_US',	'LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_TURKEY_HAPPY',
	'I suppose we could do this in a spirit of almsgiving.'),
	('en_US',	'LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_VIETNAM_HAPPY',
	'Your offer will benefit Vietnam.'),
	
	-- AI Accepts Deal (Unhappy)
	('en_US',	'LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_AUSTRALIA_UNHAPPY',
	'That is all for now.'),
	('en_US',	'LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_INDONESIA_UNHAPPY',
	'We can live with this.'),
	('en_US',	'LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_MALAYSIA_UNHAPPY',
	'This shall suffice, for now.'),
	('en_US',	'LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_NETHERLANDS_UNHAPPY',
	'Well, if you insist.'),
	('en_US',	'LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_VIETNAM_UNHAPPY',
	'Fine. We will comply with this.'),

	-- AI Rejects Deal (HAPPY)
	('en_US',	'LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_CANADA_HAPPY',
	'This proposal will not work for us. We are sorry.'),
	('en_US',	'LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_INDONESIA_HAPPY',
	'I don’t like it, but I understand.'),
	('en_US',	'LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_MALAYSIA_HAPPY',
	'We’d appreciate a better deal than this.'),
	('en_US',	'LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_MALI_HAPPY',
	'This is an unworthy offer.'),
	('en_US',	'LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_NETHERLANDS_HAPPY',
	'We need to decline. Sorry.'),
	('en_US',	'LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_POLAND_HAPPY',
	'That is troubling.'),
	('en_US',	'LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_TURKEY_HAPPY',
	'No, sorry.'),
	('en_US',	'LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_VIETNAM_HAPPY',
	'The needs of our people must come first. We cannot accept this.'),
	
	-- AI Rejects Deal (Unhappy)
	('en_US',	'LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_AUSTRALIA_UNHAPPY',
	'Your offer is an insult to Australia.'),
	('en_US',	'LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_INDONESIA_UNHAPPY',
	'That offer is almost offensive.'),
	('en_US',	'LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_MALAYSIA_UNHAPPY',
	'Do you take us for a fool?'),
	('en_US',	'LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_NETHERLANDS_UNHAPPY',
	'This is not acceptable at all. We refuse your deal.'),
	('en_US',	'LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_POLAND_UNHAPPY',
	'Certainly not.'),
	('en_US',	'LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_TURKEY_UNHAPPY',
	'Impossible.'),
	('en_US',	'LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_VIETNAM_UNHAPPY',
	'Stop wasting our time. Make a reasonable offer, or go.'),


-- Diplos | Denounce
	

	-- Human denounce, AI responds
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_HUMAN_LEADER_AMERICA_ANY',
	'How dare you insult the Americans and our fair leadership!'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_HUMAN_LEADER_ARABIA_ANY',
	'You arrogance will be your undoing.'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_HUMAN_LEADER_AUSTRALIA_ANY',
	'Your slander of Australia and her people will be known far and wide when your enfeebled nation crumbles!'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_HUMAN_LEADER_BRAZIL_ANY',
	'Do not think that we are intimidated by you. All you have are your insults.'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_HUMAN_LEADER_CHINA_PRC_ANY',
	'This insult to China will not be forgotten.'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_HUMAN_LEADER_COLOMBIA_ANY',
	'Tyrant! Oppressor of the people! Foe of liberty! Your day of reckoning approaches!'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_HUMAN_LEADER_CUBA_ANY',
	'Your threats mean little to Cuba. Either act, or walk away!'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_HUMAN_LEADER_EGYPT_ANY',
	'You dare insult Egypt?!? You will regret this!'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_HUMAN_LEADER_ETHIOPIA_ANY',
	'Your rule is a disgrace, your words are lies, and we will show the world your treacherous heart.'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_HUMAN_LEADER_FRANCE_ANY',
	'The glory and might of France will not be tarnished by such obvious lies.'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_HUMAN_LEADER_INDIA_ANY',
	'And so you show your true face. No matter. India will persevere.'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_HUMAN_LEADER_INDONESIA_ANY',
	'You call that an insult to Indonesia? A pathetic attempt from a crusted barnacle!'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_HUMAN_LEADER_JAPAN_ANY',
	'Empty words are no threat. Japan stands proud, we have no need for your approval.'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_HUMAN_LEADER_MALAYSIA_ANY',
	'Words often fall on deaf ears when they are spoken by those who deserve no respect. Who are you again?'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_HUMAN_LEADER_MEXICO_ANY',
	'You have broken the climate of harmony and cordiality between our peoples. Mexico cannot tolerate you.'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_HUMAN_LEADER_MOROCCO_ANY',
	'Is this what it has come to? That we have made the wrong decisions? We will let everyone know about your crimes!'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_HUMAN_LEADER_NETHERLANDS_ANY',
	'We give you the benefit of our frank opinion: That you are unfit to rule, and a threat to the Netherlands.'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_HUMAN_LEADER_NIGERIA_ANY',
	'You think your threats scare us? We’re humilated at your impotent rage.'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_HUMAN_LEADER_PAKISTAN_ANY',
	'So you have shown your true colors. No matter, we have no need of you.'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_HUMAN_LEADER_PHILIPPINES_ANY',
	'At long last, an enemy makes themselves known. We should have expected as much from you.'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_HUMAN_LEADER_POLAND_ANY',
	'You’re insulting Poland now? Our conscience is clean. We have nothing to hide.'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_HUMAN_LEADER_SOUTH_AFRICA_ANY',
	'Your petty insults are nothing compared to the struggle the South Africans have overcome.'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_HUMAN_LEADER_THAILAND_ANY',
	'The wellbeing of our people belies your false words.'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_HUMAN_LEADER_UK_ANY',
	'The government wishes to warn those who disrespect her people, and her mandate of the manifold troubles that will ensue.'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_HUMAN_LEADER_UKRAINE_ANY',
	'I do not have to take such an insult. You will regret your decision.'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_HUMAN_LEADER_VIETNAM_ANY',
	'You cannot content yourself with ruling your own people, but you must interfere with ours as well? We shall tell the whole world of your crimes!'),
	
	-- From AI
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_AMERICA_ANY',
	'We cannot abide a ruler without dignity, and the world must be made aware. (Denounces You)'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_ARABIA_ANY',
	'You are a wicked one. The world must know now. (Denounces You)'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_AUSTRALIA_ANY',
	'The reprehensible words and actions you’ve demonstrated can only lead your people down a path of ignorance and destitution. (Denounces You)'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_BRAZIL_ANY',
	'Tolerance does not mean "anything goes". And your actions have proven intolerable. (Denounces You)'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_CHINA_PRC_ANY',
	'Your reputation will be forever tarnished. (Denounces You)'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_COLOMBIA_ANY',
	'Perhaps you can deceive others, but we have no illusions about your wicked designs. (Denounces You)'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_CUBA_ANY',
	'Your actions bring shame to the civilizations of the world! (Denounces You)'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_EGYPT_ANY',
	'Your offenses are many. Let the world judge who you truly are. (Denounces You)'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_ETHIOPIA_ANY',
	'Are all your words impious? Are all your deeds deceitful? Ethiopia sees nothing redeeming in your rule. (Denounces You)'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_FRANCE_ANY',
	'We don’t like the look of what you’ve been up to. What would your friends think of this information? (Denounces You)'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_GERMANY_ANY',
	'The world will know of your treachery. And you will be judged. (Denounces You)'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_INDIA_ANY',
	'You are untrustworthy; this is the worst kind of violence. (Denounces You)'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_INDONESIA_ANY',
	'You are like the muck that spreads around ships in calm waters. When in your presence, it is best to sail away. (Denounces You)'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_IRELAND_ANY',
	'Your ways are simply too cruel for this world, and we cannot sit back idly any longer. (Denounces You)'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_ITALY_ANY',
	'You are a disgrace. Italy will tell the world, they will know who you truly are. (Denounces You)'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_JAPAN_ANY',
	'You are a foolish, simple leader. And your people should know the truth. (Denounces You)'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_KAZAKHSTAN_ANY',
	'You are a wretched liar, and cannot be trusted to Kazakhstan! You are the worst of your kind. (Denounces You)'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_MALAYSIA_ANY',
	'A strong economy today is how we prepare for tomorrow. We see no future for your country. (Denounces You)'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_MEXICO_ANY',
	'Wherever there’s corruption, people have to denounce it. (Denounces You)'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_MOROCCO_ANY',
	'To see you having fallen so far from grace... it punishes our hearts. (Denounces You)'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_NETHERLANDS_ANY',
	'It is our fervent desire to tell you just how awful we find you, and we wish your years in office to be brief. (Denounces You)'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_NIGERIA_ANY',
	'You are nothing but a criminal. The world must know. (Denounces You)'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_NORWAY_ANY',
	'There will be no place for you at Norway’s table. You are disgraceful. (Denounces You)'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_PAKISTAN_ANY',
	'You’re the definition of hopeless. Your many offenses must be made known to the world. (Denounces You)'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_PHILIPPINES_ANY',
	'To be happy does not mean to indulge in foolishness. (Denounces You)'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_POLAND_ANY',
	'Evil cannot stay hidden for long. God will always bring it to light. (Denounces You)'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_RUSSIA_ANY',
	'We have seen much in our lives, but we have never seen such a despicable leader. You should be ashamed, and will be. (Denounces You)'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_SOUTH_AFRICA_ANY',
	'We have had enough of your bad behavior. South Africa condemns you before the world. (Denounces You)'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_THAILAND_ANY',
	'I have never seen such ignominious behavior. How can you think yourself fit to rule a nation? (Denounces You)'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_UK_ANY',
	'We will have nothing to do with your administration. You are hereby denounced. (Denounces You)'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_UKRAINE_ANY',
	'We hate to do this to you, but... you have betrayed Ukraine’s trust too many times. You are denounced. (Denounces You)'),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_VIETNAM_ANY',
	'Look here, you snake. One day, there will be a great reckoning between our peoples, and justice will be served to you. (Denounces You)'),
	

-- Diplos | Declarations of War
	

	-- Human Declares War, AI responds
	('en_US',	'LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_AMERICA_ANY',
	'If we were to choose between righteousness and peace, we choose righteousness.'),
	('en_US',	'LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_ARGENTINA_ANY',
	'With fighting, no one wins. Why do you choose to fight?'),
	('en_US',	'LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_CANADA_ANY',
	'As we can reach no peaceful resolution with you, Canada must turn, with reluctance, to war.'),
	('en_US',	'LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_CUBA_ANY',
	'Really now? Cuba has stood firm against the most powerful empires of history! You will not stop us.'),
	('en_US',	'LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_ICELAND_ANY',
	'Our men are tough, or they would not have settled here. Do you truly think your warriors can match their mettle?'),
	('en_US',	'LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_INDONESIA_ANY',
	'Truly? Didn’t you know our vengeance puts leaders to shame? Soon you will.'),
	('en_US',	'LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_ISRAEL_ANY',
	'We will defend our home with boundless courage. We will win, or die.'),
	('en_US',	'LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_MALAYSIA_ANY',
	'We applaud your bravery, but your intelligence leaves much to be desired.'),
	('en_US',	'LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_MALI_ANY',
	'Enough! Our forbearance ends here! We must have war between us, instead of a false peace.'),
	('en_US',	'LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_MOROCCO_ANY',
	'We will not back away from a fight. Morocco will persevere!'),
	('en_US',	'LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_NETHERLANDS_ANY',
	'Your treacherous aggression shall not succeed. The Netherlands resists!'),
	('en_US',	'LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_NIGERIA_ANY',
	'We are no strangers to conflict. If you want a fight, you will have one.'),
	('en_US',	'LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_PAKISTAN_ANY',
	'You will regret this. We will defend Pakistan to the death.'),
	('en_US',	'LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_PHILIPPINES_ANY',
	'We’ve seen revolutions rise from the written word, and enemies fall by the sword. The Philippines will not succumb before foreigners.'),
	('en_US',	'LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_PORTUGAL_ANY',
	'What has Portugal done to offend you so? Oh well, it is too late to fix this mistake. How regrettable, that we must go to war.'),
	('en_US',	'LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_RUSSIA_ANY',
	'Your war is hopeless. You have not learned from history - conquering Russia is impossible.'),
	('en_US',	'LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_SOUTH_AFRICA_ANY',
	'You want war? We are willing to fight and die for South Africa!'),
	('en_US',	'LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_SPAIN_ANY',
	'You think your army can compare with the Spanish armada... with the might of our empire? You are grievously mistaken.'),
	('en_US',	'LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_SWEDEN_ANY',
	'Sweden will chastise those who threaten the world. Prepare yourself for war.'),
	('en_US',	'LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_THAILAND_ANY',
	'We are a peaceful nation, but do not think we will shy away from battle!'),
	('en_US',	'LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_TURKEY_ANY',
	'Good. The world shall witness the incontestable might of our armies and the glory of Turkey.'),
	('en_US',	'LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_VIETNAM_ANY',
	'We have waited for this day for a long time. Today begins the war that will end in your destruction.'),
	
	-- AI Declares War
	('en_US',	'LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_AMERICA_ANY',
	'We wanted to avoid this, you know, but your idea of peace left the United States of America no choice.'),
	('en_US',	'LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_ARABIA_ANY',
	'It is a shame that Saudi Arabia must resort to violence, but we must do it. It is not the custom of a country’s ruler to kill another.'),
	('en_US',	'LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_ARGENTINA_ANY',
	'A united Argentina is unstoppable. And today, we are united against you. Prepare for war!'),
	('en_US',	'LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_BRAZIL_ANY',
	'Brazil has to do this, for the sake of progress, if nothing else. You must be opposed.'),
	('en_US',	'LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_CANADA_ANY',
	'As an unstinting malignancy defines your relationship to Canada, we have no recourse than war.'),
	('en_US',	'LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_CUBA_ANY',
	'Your imperialistic aspirations are too much for the world to bear. It is time someone did something about it.'),
	('en_US',	'LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_ETHIOPIA_ANY',
	'Your actions insult the people of Ethiopia, and for that you must pay a heavy price.'),
	('en_US',	'LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_FRANCE_ANY',
	'You have insulted France for the very last time. It’s time we start this war.'),
	('en_US',	'LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_GERMANY_ANY',
	'Let it be known: you are an enemy of Germany, and must be destroyed. May god have mercy on you, for we will not.'),
	('en_US',	'LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_GREECE_ANY',
	'This is for the greater good. You will understand... in time.'),
	('en_US',	'LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_INDONESIA_ANY',
	'Before this war ends, you will know the fury of a thousand ships.'),
	('en_US',	'LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_IRELAND_ANY',
	'This brings us a great deal of pain, but we simply cannot sit by and watch as you commit atrocities against the peoples of the world.'),
	('en_US',	'LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_ISRAEL_ANY',
	'We will attack anyone who threatens Israel and her people. You are a threat.'),
	('en_US',	'LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_ITALY_ANY',
	'Prepare yourselves for war. Our armies will stop at nothing; our navies will swarm your shores, for Italy’s glory.'),
	('en_US',	'LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_MALAYSIA_ANY',
	'We take no pleasure in this decision, but you have forced our hand. Your tyranny ends here.'), 
	('en_US',	'LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_MOROCCO_ANY',
	'Enough is enough. The time has come for you to answer for your sins.'),
	('en_US',	'LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_NETHERLANDS_ANY',
	'The Netherlands does not fear you. When we defeat you, we will be stronger than ever.'),
	('en_US',	'LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_NIGERIA_ANY',
	'A Nigerian prefers to face their enemies head on. Let us see what you are made of.'),
	('en_US',	'LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_PAKISTAN_ANY',
	'We have decided that the status quo is unacceptable. It is time for war.'), 
	('en_US',	'LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_PHILIPPINES_ANY',
	'The tyranny of some is possible only through the cowardice of others. The world has suffered your insolence long enough, and you must be stopped.'), 
	('en_US',	'LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_PORTUGAL_ANY',
	'We have declared war against you. We did not want to do this, but we don’t want you around anymore, either.'),
	('en_US',	'LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_RUSSIA_ANY',
	'I hereby proclaim you an enemy to Russia, our allies, and God, may he have mercy on your soul.'),
	('en_US',	'LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_SPAIN_ANY',
	'You have transgressed against our kingdom, and the kingdom of God... you must answer for your sins.'),
	('en_US',	'LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_SWEDEN_ANY',
	'Sweden will do her part to push back the evils of the world. War is one way to do this.'),
	('en_US',	'LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_THAILAND_ANY',
	'We do this for the well being of the world and of Thailand. All will be happier when you are brought down!'),
	('en_US',	'LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_TURKEY_ANY',
	'Your continued insolence and failure to recognize Turkish preeminence leads us to war.'),
	('en_US',	'LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_VIETNAM_ANY',
	'Now you are at war with Vietnam. Do you hear our trumpets? The thunder of our elephants? They are coming for you!'),
	('en_US',	'LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_UK_ANY',
	'As our protests are in vain, we hereby declare war.'),


-- Diplos | Make Peace
	
	
	-- AI accepts from human
	('en_US',	'LOC_DIPLO_MAKE_PEACE_AI_ACCEPT_DEAL_LEADER_VIETNAM_ANY',
	'Enough bloodshed. Let our citizens rebuild their homes.'),
	
	-- AI refuses human
	('en_US',	'LOC_DIPLO_MAKE_PEACE_AI_REFUSE_DEAL_LEADER_VIETNAM_ANY',
	'Never! We will not bow to you.'),
	
	-- AI requests from human
	('en_US',	'LOC_DIPLO_MAKE_PEACE_FROM_AI_LEADER_VIETNAM_ANY',
	'Shall we set aside our arms?'),


-- Diplos | Defeat
	
	
	-- AI is Defeated
	('en_US',	'LOC_DIPLO_DEFEAT_FROM_AI_LEADER_AMERICA_ANY',
	'Congratulations. Instead of the United States of America, your nation will go far.'),
	('en_US',	'LOC_DIPLO_DEFEAT_FROM_AI_LEADER_ARABIA_ANY',
	'This is not victory. "Victory" is changing the hearts of your opponents; through gentleness, through kindness.'),
	('en_US',	'LOC_DIPLO_DEFEAT_FROM_AI_LEADER_AUSTRALIA_ANY',
	'We may be down, but we are not out. The Aussie spirit remains unbroken.'),
	('en_US',	'LOC_DIPLO_DEFEAT_FROM_AI_LEADER_BRAZIL_ANY',
	'The light of Brazil is extinguished. This is a great tragedy!'),
	('en_US',	'LOC_DIPLO_DEFEAT_FROM_AI_LEADER_CANADA_ANY',
	'So ends our dream of a Canada that might have been. Our people are good-hearted. Rule with mercy, and learn from them.'),
	('en_US',	'LOC_DIPLO_DEFEAT_FROM_AI_LEADER_CHINA_PRC_ANY',
	'This is a grave crisis. The Party is defeated. I am defeated. What will become of China?'),
	('en_US',	'LOC_DIPLO_DEFEAT_FROM_AI_LEADER_CHINA_ROC_ANY',
	'We never thought this could happen... not like this.'),
	('en_US',	'LOC_DIPLO_DEFEAT_FROM_AI_LEADER_ETHIOPIA_ANY',
	'Do you think God abandoned Ethiopia? Do you think his favor rests on you? Do not gloat in your victory today.'),
	('en_US',	'LOC_DIPLO_DEFEAT_FROM_AI_LEADER_FRANCE_ANY',
	'The French have lived long enough to know when we’re defeated. Carry on.'),
	('en_US',	'LOC_DIPLO_DEFEAT_FROM_AI_LEADER_GERMANY_ANY',
	'We were the august and glorious… but no, never mind that. You are victorious. May your reign be more peaceful than ours ever was.'),
	('en_US',	'LOC_DIPLO_DEFEAT_FROM_AI_LEADER_GREECE_ANY',
	'You may have defeated us, but what we leave behind is woven into the lives of others.'),
	('en_US',	'LOC_DIPLO_DEFEAT_FROM_AI_LEADER_ICELAND_ANY',
	'And thus our journey comes to an end. At least the Icelandic story will live on in history.'),
	('en_US',	'LOC_DIPLO_DEFEAT_FROM_AI_LEADER_INDIA_ANY',
	'You may have vanquished the Indian armies... but you will never vanquish the Indian spirit.'),
	('en_US',	'LOC_DIPLO_DEFEAT_FROM_AI_LEADER_INDONESIA_ANY',
	'You may have conquered our islands, but our people remain unbowed.'),
	('en_US',	'LOC_DIPLO_DEFEAT_FROM_AI_LEADER_ISRAEL_ANY',
	'Do not glory in your conquest. One day you may see your capital bathed in flame.'),
	('en_US',	'LOC_DIPLO_DEFEAT_FROM_AI_LEADER_JAPAN_ANY',
	'This is a day of great shame and sadness for Japan. Please end this dishonor to our people.'),
	('en_US',	'LOC_DIPLO_DEFEAT_FROM_AI_LEADER_NEW_ZEALAND_ANY',
	'We have done our utmost, but your strength was greater. Our hearts, at least, will beat undefeated.'),
	('en_US',	'LOC_DIPLO_DEFEAT_FROM_AI_LEADER_NIGERIA_ANY',
	'We fought hard, but could not prevail. Today, the victory is yours.'),
	('en_US',	'LOC_DIPLO_DEFEAT_FROM_AI_LEADER_PAKISTAN_ANY',
	'We grieve for Pakistan. May you be cursed for your actions this day.'),
	('en_US',	'LOC_DIPLO_DEFEAT_FROM_AI_LEADER_RUSSIA_ANY',
	'Russia is defeated. To live one’s life is not like crossing a field.'),
	('en_US',	'LOC_DIPLO_DEFEAT_FROM_AI_LEADER_SWEDEN_ANY',
	'Sweden has never loved power, and now we are left without our culture. Only regret and loss remain for us.'),
	('en_US',	'LOC_DIPLO_DEFEAT_FROM_AI_LEADER_THAILAND_ANY',
	'Thailand may fall today, but we have suffered defeats before, and we will ascend again.'),
	('en_US',	'LOC_DIPLO_DEFEAT_FROM_AI_LEADER_UK_ANY',
	'This severe and afflicting loss will not be sustained, and the United Kingdom, thank providence, will ascend again.'),
	('en_US',	'LOC_DIPLO_DEFEAT_FROM_AI_LEADER_VIETNAM_ANY',
	'You have defeated Vietnam. Our cities ruined, our troops killed.'),

	-- Human is Defeated (will see this in hotseat)
	('en_US',	'LOC_DIPLO_DEFEAT_FROM_HUMAN_LEADER_VIETNAM_ANY',
	'{LOC_DIPLO_DEFEAT_FROM_AI_LEADER_VIETNAM_ANY}');