--==========================================================================================================================
											-- NAMED PLACES --
--==========================================================================================================================
INSERT INTO LocalizedText
		(Language, Tag, Text)
VALUES	("en_US",	"LOC_NAMED_LAKE_WIVENHOE_NAME",					"Lake Wivenhoe"),
		("en_US",	"LOC_NAMED_RIVER_GUDENA_NAME",					"Gudenå"),
		("en_US",	"LOC_NAMED_RIVER_KONGEAEN_NAME",				"Kongeåen"),
		("en_US",	"LOC_NAMED_RIVER_ODENSE_NAME",					"Odense River"),
		("en_US",	"LOC_NAMED_RIVER_POLEA_NAME",					"Pøleå"),
		("en_US",	"LOC_NAMED_RIVER_VARDE_NAME",					"Varde"),
		("en_US",	"LOC_NAMED_RIVER_SUSA_NAME",					"Suså"),
		("en_US",	"LOC_NAMED_RIVER_VEJLE_NAME",					"Vejle River"),
		("en_US",	"LOC_NAMED_MOUNTAIN_MOLLEHOJ_NAME",				"Møllehøj"),
		("en_US",	"LOC_NAMED_MOUNTAIN_YDING_NAME",				"Yding Skovhøj"),
		("en_US",	"LOC_NAMED_MOUNTAIN_EJER_NAME",					"Ejer Bavnehøj"),
		("en_US",	"LOC_NAMED_MOUNTAIN_LINDBJERG_NAME",			"Lindbjerg"),
		("en_US",	"LOC_NAMED_MOUNTAIN_MARGRETELYST_NAME",			"Margretelyst Sø"),
		("en_US",	"LOC_NAMED_MOUNTAIN_VISTOFTE_NAME",				"Vistofte"),
		("en_US",	"LOC_NAMED_MOUNTAIN_RYTTERKNAEGTEN_NAME",		"Rytterknægten"),
		("en_US",	"LOC_NAMED_MOUNTAIN_HIMMELBJERGET_NAME",		"Himmelbjerget"),
		("en_US",	"LOC_NAMED_MOUNTAIN_ABORREBJERG_NAME",			"Aborrebjerg"),
		("en_US",	"LOC_NAMED_LAKE_ARRESO_NAME",					"Arresø"),
		("en_US",	"LOC_NAMED_LAKE_ESRUM_NAME",					"Lake Esrum"),
		("en_US",	"LOC_NAMED_LAKE_STADIL_NAME",					"Stadil Fjord"),
		("en_US",	"LOC_NAMED_LAKE_MOSSO_NAME",					"Mossø"),
		("en_US",	"LOC_NAMED_LAKE_SALTBAEK_NAME",					"Saltbæk Vig"),
		("en_US",	"LOC_NAMED_LAKE_TISSO_NAME",					"Tissø"),
		("en_US",	"LOC_NAMED_LAKE_FURESO_NAME",					"Furesø"),
		("en_US",	"LOC_NAMED_LAKE_SKANDERBORG_NAME",				"Skanderborg Sø"),
		("en_US",	"LOC_NAMED_SEA_ORESUND_NAME",					"Øresund"),
		("en_US",	"LOC_NAMED_RIVER_KEMIJOKI_NAME",				"Kemijoki"),
		("en_US",	"LOC_NAMED_RIVER_IIJOKI_NAME",					"Iijoki"),
		("en_US",	"LOC_NAMED_RIVER_OUNASJOKI_NAME",				"Ounasjoki"),
		("en_US",	"LOC_NAMED_RIVER_KITINEN_NAME",					"Kitinen"),
		("en_US",	"LOC_NAMED_RIVER_LUIRO_NAME",					"Luiro"),
		("en_US",	"LOC_NAMED_RIVER_KYMI_NAME",					"Kymi"),
		("en_US",	"LOC_NAMED_RIVER_SIMOJOKI_NAME",				"Simojoki"),
		("en_US",	"LOC_NAMED_RIVER_MUONIO_NAME",					"Muonio"),
		("en_US",	"LOC_NAMED_RIVER_VUOKSI_NAME",					"Vuoksi"),
		("en_US",	"LOC_NAMED_MOUNTAIN_KARELIDES_NAME",			"Karelides"),
		("en_US",	"LOC_NAMED_VOLCANO_AITOLAHTI_NAME",				"Aitolahti"),
		("en_US",	"LOC_NAMED_LAKE_ROINE_NAME",					"Lake Roine"),
		("en_US",	"LOC_NAMED_LAKE_PAIJANNE_NAME",					"Lake Päijänne"),
		("en_US",	"LOC_NAMED_LAKE_INARI_NAME",					"Lake Inari"),
		("en_US",	"LOC_NAMED_LAKE_OULUJARVI_NAME",				"Lake Oulujärvi"),
		("en_US",	"LOC_NAMED_LAKE_PIELINEN_NAME",					"Lake Pielinen"),
		("en_US",	"LOC_NAMED_LAKE_PIHLAJAVESI_NAME",				"Lake Pihlajavesi"),
		("en_US",	"LOC_NAMED_LAKE_NASIJARVI_NAME",				"Lake Näsijärvi"),
		("en_US",	"LOC_NAMED_LAKE_KALLAVESI_NAME",				"Lake Kallavesi"),
		("en_US",	"LOC_NAMED_LAKE_ORIVESI_NAME",					"Lake Orivesi"),
		("en_US",	"LOC_NAMED_LAKE_HAUKIVESI_NAME",				"Lake Haukivesi"),
		("en_US",	"LOC_NAMED_LAKE_PYHASELKA_NAME",				"Lake Pyhäselkä"),
		("en_US",	"LOC_NAMED_LAKE_PUULA_NAME",					"Lake Puula"),
		("en_US",	"LOC_NAMED_LAKE_HOYTIANEN_NAME",				"Lake Höytiäinen"),
		("en_US",	"LOC_NAMED_RIVER_THJORSA_NAME",					"Þjórsá River"),
		("en_US",	"LOC_NAMED_RIVER_HVITA_NAME",					"Hvítá River"),
		("en_US",	"LOC_NAMED_RIVER_FNJOSKA_NAME",					"Fnjóská River"),
		("en_US",	"LOC_NAMED_RIVER_KUTHAFLJOT_NAME",				"Kúðafljót River"),
		("en_US",	"LOC_NAMED_RIVER_SKJALFANDAFLJOT_NAME",			"Skjálfandafljót"),
		("en_US",	"LOC_NAMED_RIVER_JOKULSA_A_FJOLLUM_NAME",		"Jökulsá á Fjöllum"),
		("en_US",	"LOC_NAMED_RIVER_JOKULSA_A_DAL_NAME",			"Jökulsá á Dal"),
		("en_US",	"LOC_NAMED_MOUNTAIN_ESJAN_NAME",				"Esjan"),
		("en_US",	"LOC_NAMED_MOUNTAIN_HOFSJOKULL_NAME",			"Hofsjökull"),
		("en_US",	"LOC_NAMED_MOUNTAIN_VATNAJOKULL_NAME",			"Vatnajökull"),
		("en_US",	"LOC_NAMED_MOUNTAIN_LANGJOKULL_NAME",			"Langjökull"),
		("en_US",	"LOC_NAMED_MOUNTAIN_MYRDALSJOKULL_NAME",		"Mýrdalsjökull"),
		("en_US",	"LOC_NAMED_MOUNTAIN_LANDMANNALAUGAR_NAME",		"Landmannalaugar Mountains"),
		("en_US",	"LOC_NAMED_VOLCANO_HEKLA_NAME",					"Hekla Volcano"),
		("en_US",	"LOC_NAMED_VOLCANO_BARTHARBUNGA_NAME",			"Bárðarbunga"),
		("en_US",	"LOC_NAMED_VOLCANO_KATLA_NAME",					"Katla Volcano"),
		("en_US",	"LOC_NAMED_VOLCANO_KRAFLA_CALDERA_NAME",		"Krafla Caldera"),
		("en_US",	"LOC_NAMED_VOLCANO_ASKJA_CALDERA_NAME",			"Askja Caldera"),
		("en_US",	"LOC_NAMED_VOLCANO_ELDFELL_NAME",				"Eldfell Volcano"),
		("en_US",	"LOC_NAMED_VOLCANO_THRIHNJUKAGIGUR_NAME",		"Þríhnjúkagígur"),
		("en_US",	"LOC_NAMED_LAKE_THINGVALLAVATN_NAME",			"Þingvallavatn"),
		("en_US",	"LOC_NAMED_LAKE_MYVATN_NAME",					"Mývatn"),
		("en_US",	"LOC_NAMED_LAKE_KERITH_NAME",					"Kerið"),
		("en_US",	"LOC_NAMED_LAKE_OSKJUVATN_NAME",				"Öskjuvatn"),
		("en_US",	"LOC_NAMED_LAKE_JOKULSARLON_NAME",				"Jökulsárlón"),
		("en_US",	"LOC_NAMED_LAKE_LAGARFLJOT_NAME",				"Lagarfljót"),
		("en_US",	"LOC_NAMED_LAKE_HVITARVATN_NAME",				"Hvítárvatn"),
		("en_US",	"LOC_NAMED_SEA_BAKKAFLOI_NAME",					"Bakkaflói"),
		("en_US",	"LOC_NAMED_SEA_FAXAFLOI_NAME",					"Faxaflói"),
		("en_US",	"LOC_NAMED_SEA_GRUNNAVIK_NAME",					"Grunnavík"),
		("en_US",	"LOC_NAMED_SEA_HERADSFLOI_NAME",				"Héradsflói"),
		("en_US",	"LOC_NAMED_SEA_HUNAFLOI_NAME",					"Húnaflói"),
		("en_US",	"LOC_NAMED_SEA_THISTILFJORTHUR_NAME",			"Þistilfjörður"),
		("en_US",	"LOC_NAMED_SEA_BREITHAFJORTHUR_NAME",			"Breiðafjörður"),
		("en_US",	"LOC_NAMED_SEA_ISAFJARTHARDJUP_NAME",			"Ísafjarðardjúp"),
		("en_US",	"LOC_NAMED_SEA_SKAGAFJORTHUR_NAME",				"Skagafjörður"),
		("en_US",	"LOC_NAMED_SEA_EYJAFJORTHUR_NAME",				"Eyjafjörður"),
		("en_US",	"LOC_NAMED_RIVER_MANGOKY_NAME",					"Mangoky River"),
		("en_US",	"LOC_NAMED_RIVER_ONILAHY_NAME",					"Onilahy River"),
		("en_US",	"LOC_NAMED_RIVER_BETSIBOKA_NAME",				"Betsiboka River"),
		("en_US",	"LOC_NAMED_RIVER_MATSIATRA_NAME",				"Matsiatra River"),
		("en_US",	"LOC_NAMED_RIVER_MANAMBOLO_NAME",				"Manambolo River"),
		("en_US",	"LOC_NAMED_RIVER_MANANANTANANA_NAME",			"Mananantanana River"),
		("en_US",	"LOC_NAMED_RIVER_IKOSY_NAME",					"Ikosy River"),
		("en_US",	"LOC_NAMED_RIVER_TSIRIBIHINA_NAME",				"Tsiribihina River"),
		("en_US",	"LOC_NAMED_MOUNTAIN_TSARATANANA_NAME",			"Massif du Tsaratanana"),
		("en_US",	"LOC_NAMED_MOUNTAIN_ANKARATRA_NAME",			"Ankaratra"),
		("en_US",	"LOC_NAMED_MOUNTAIN_ANDRINGITRA_NAME",			"Andringitra Massif"),
		("en_US",	"LOC_NAMED_MOUNTAIN_LAVASOA_NAME",				"Lavasoa-Ambatotsirongorongo Mountains"),
		("en_US",	"LOC_NAMED_VOLCANO_BOBAOMBY_NAME",				"Ambre-Bobaomby"),
		("en_US",	"LOC_NAMED_VOLCANO_ANKAIZINA_NAME",				"Ankaizina Field"),
		("en_US",	"LOC_NAMED_VOLCANO_ANKARATRA_NAME",				"Ankaratra Field"),
		("en_US",	"LOC_NAMED_VOLCANO_ITASY_NAME",					"Itasy Volcano"),
		("en_US",	"LOC_NAMED_VOLCANO_NOSYBE_NAME",				"Nosy-Be"),
		("en_US",	"LOC_NAMED_LAKE_ALAOTRA_NAME",					"Lake Alaotra"),
		("en_US",	"LOC_NAMED_LAKE_ANOSY_NAME",					"Lake Anosy"),
		("en_US",	"LOC_NAMED_LAKE_IHOTRY_NAME",					"Lake Ihotry"),
		("en_US",	"LOC_NAMED_LAKE_KINKONY_NAME",					"Lake Kinkony"),
		("en_US",	"LOC_NAMED_LAKE_MANDRAKA_NAME",					"Lake Mandraka"),
		("en_US",	"LOC_NAMED_LAKE_MANTASOA_NAME",					"Lake Mantasoa"),
		("en_US",	"LOC_NAMED_LAKE_TRITRIVA_NAME",					"Lake Tritriva"),
		("en_US",	"LOC_NAMED_LAKE_TSIMANAPETSOTSOA_NAME",			"Lake Tsimanapetsotsoa"),
		("en_US",	"LOC_NAMED_SEA_AMBARO_BAY_NAME",				"Ambaro Bay"),
		("en_US",	"LOC_NAMED_SEA_BAIE_ANDOVOBATOFOTSY_NAME",		"Baie Andovobatofotsy"),
		("en_US",	"LOC_NAMED_SEA_BAIE_ANDOVOBAZAH_NAMEA",			"Baie Andovobazaha"),
		("en_US",	"LOC_NAMED_SEA_BAIE_DE_BALY_NAME",				"Baie de Baly"),
		("en_US",	"LOC_NAMED_SEA_BAIE_DE_TINTINGUE_NAME",			"Baie de Tintingue"),
		("en_US",	"LOC_NAMED_SEA_BAY_OF_LAKY_NAME",				"Bay of Laky"),
		("en_US",	"LOC_NAMED_SEA_BEFOTAKA_BAY_NAME",				"Betotaka Bay"),
		("en_US",	"LOC_NAMED_SEA_HELODRANO_ANTONGILA_BAY_NAME",	"Helodrano Antongila Bay"),
		("en_US",	"LOC_NAMED_SEA_HELODRANO_MAHAJAMBE_NAME",		"Helodrano Mahajambe"),
		("en_US",	"LOC_NAMED_SEA_HELODRANO_NARINDA_NAME",			"Helodrano Narinda"),
		("en_US",	"LOC_NAMED_VOLCANO_LOWER_CHINDWIN_NAME",		"Lower Chindwin Volcano"),
		("en_US",	"LOC_NAMED_VOLCANO_MOUNT_POPA_NAME",			"Mount Popa"),
		("en_US",	"LOC_NAMED_VOLCANO_TAUNGTHONTON_NAME",			"Taungthonton"),
		("en_US",	"LOC_NAMED_RIVER_MURES_NAME",					"Mureș River"),
		("en_US",	"LOC_NAMED_RIVER_OLT_NAME",						"Olt River"),
		("en_US",	"LOC_NAMED_RIVER_SIRET_NAME",					"Siret River"),
		("en_US",	"LOC_NAMED_RIVER_IALOMITA_NAME",				"Ialomița River"),
		("en_US",	"LOC_NAMED_RIVER_SOMES_NAME",					"Someș River"),
		("en_US",	"LOC_NAMED_RIVER_ARGES_NAME",					"Argeș River"),
		("en_US",	"LOC_NAMED_RIVER_JIU_NAME",						"Jiu River"),
		("en_US",	"LOC_NAMED_RIVER_BUZAU_NAME",					"Buzău River"),
		("en_US",	"LOC_NAMED_RIVER_DAMBOVITA_NAME",				"Dâmbovița River"),
		("en_US",	"LOC_NAMED_MOUNTAIN_ALMAJ_NAME",		 		"Almăj Mountains"),
		("en_US",	"LOC_NAMED_MOUNTAIN_BIHOR_NAME",				"Bihor Mountains"),
		("en_US",	"LOC_NAMED_MOUNTAIN_BUCEGI_NAME",				"Bucegi Mountains"),
		("en_US",	"LOC_NAMED_MOUNTAIN_FAGARAS_NAME",				"Făgăraş Mountains"),
		("en_US",	"LOC_NAMED_MOUNTAIN_GODEANU_NAME",				"Godeanu Mountains"),
		("en_US",	"LOC_NAMED_MOUNTAIN_RETEZAT_NAME",	 			"Retezat Mountains"),
		("en_US",	"LOC_NAMED_MOUNTAIN_VRANCEA_NAME",	 			"Vrancea Mountains"),
		("en_US",	"LOC_NAMED_MOUNTAIN_SUREANU_NAME",	 			"Şureanu Mountains"),
		("en_US",	"LOC_NAMED_MOUNTAIN_TARCU_NAME",		 		"Ţarcu Mountains"),
		("en_US",	"LOC_NAMED_VOLCANO_CIOMADUL_NAME",				"Ciomadul"),
		("en_US",	"LOC_NAMED_LAKE_BALEA_NAME",					"Lacul Bâlea"),
		("en_US",	"LOC_NAMED_LAKE_BUCURA_NAME",					"Bucara Lake"),
		("en_US",	"LOC_NAMED_LAKE_RAZIM_NAME",					"Lacul Razim"),
		("en_US",	"LOC_NAMED_LAKE_ROSU_NAME",						"Lacul Roşu"),
		("en_US",	"LOC_NAMED_LAKE_TAUL_TAPULUI_NAME",				"Tăul Țapului");
