-----------------------------------------------
-- Named Places
-----------------------------------------------
REPLACE INTO LocalizedText
		(Language, Tag, Text)
VALUES	("en_US",	"LOC_NAMED_RIVER_LOA_NAME",						"Loa River"),
		("en_US",	"LOC_NAMED_RIVER_CACHAPOAL_NAME",				"Cachapoal River"),
		("en_US",	"LOC_NAMED_RIVER_BIO_BIO_NAME",					"Bío-Bío River"),
		("en_US",	"LOC_NAMED_RIVER_MAULE_NAME",					"Maule River"),
		("en_US",	"LOC_NAMED_RIVER_BUENO_NAME",					"Bueno River"),
		("en_US",	"LOC_NAMED_RIVER_PASCUA_NAME",					"Pascua River"),
		("en_US",	"LOC_NAMED_RIVER_MAIPO_NAME",					"Maipo River"),
		("en_US",	"LOC_NAMED_RIVER_LIMARI_NAME",					"Limari River"),
		("en_US",	"LOC_NAMED_MOUNTAIN_NEVADO_NAME",				"Nevado Tres Cruces"),
		("en_US",	"LOC_NAMED_MOUNTAIN_TUNPUNGATO_NAME",			"Tupungato"),
		("en_US",	"LOC_NAMED_MOUNTAIN_EL_MUERTO_NAME",			"El Muerto"),
		("en_US",	"LOC_NAMED_MOUNTAIN_PARINACOTA_NAME",			"Parinacota"),
		("en_US",	"LOC_NAMED_MOUNTAIN_POMERAPE_NAME",				"Pomerape"),
		("en_US",	"LOC_NAMED_MOUNTAIN_TRES_NAME",					"Tres Quebradas"),
		("en_US",	"LOC_NAMED_MOUNTAIN_OLIVARES_NAME",				"Olivares"),
		("en_US",	"LOC_NAMED_MOUNTAIN_ALTO_NAME",					"Alto"),
		("en_US",	"LOC_NAMED_MOUNTAIN_MARMOLEJO_NAME",			"Marmolejo"),
		("en_US",	"LOC_NAMED_MOUNTAIN_SAN_PABLO_NAME",			"San Pablo"),
		("en_US",	"LOC_NAMED_VOLCANO_OJOS_NAME",					"Ojos del Salado"),
		("en_US",	"LOC_NAMED_VOLCANO_LLULLAILLACO_NAME",			"Llullaillaco"),
		("en_US",	"LOC_NAMED_VOLCANO_INCAHUASI_NAME",				"Incahuasi"),
		("en_US",	"LOC_NAMED_VOLCANO_TUPUNGATO_NAME",				"Tunpungato"),
		("en_US",	"LOC_NAMED_VOLCANO_PARINACOTA_NAME",			"Parinacota"),
		("en_US",	"LOC_NAMED_VOLCANO_PULAR_NAME",					"Pular"),
		("en_US",	"LOC_NAMED_VOLCANO_EL_SOLO_NAME",				"El Solo"),
		("en_US",	"LOC_NAMED_VOLCANO_AUCANQUILCHA_NAME",			"Aucanquilcha"),
		("en_US",	"LOC_NAMED_VOLCANO_SAN_PEDRO_NAME",				"San Pedro"),
		("en_US",	"LOC_NAMED_VOLCANO_SIERRA_NEVADA_NAME",			"Sierra Nevada de Lagunas Bravas"),
		("en_US",	"LOC_NAMED_VOLCANO_WALLATIRI_NAME",				"Wallatiri"),
		("en_US",	"LOC_NAMED_VOLCANO_ACOTANGO_NAME",				"Acotango"),
		("en_US",	"LOC_NAMED_DESERT_ATACAMA_NAME",				"Atacama Desert"),
		("en_US",	"LOC_NAMED_DESERT_MONTE_NAME",					"Monte Desert"),
		("en_US",	"LOC_NAMED_DESERT_PATAGONIAN_NAME",				"Patagonian Desert"),
		("en_US",	"LOC_NAMED_LAKE_GENERAL_CARRERA_NAME",			"General Carrera"),
		("en_US",	"LOC_NAMED_LAKE_LLANQUIHUE_NAME",				"Lake Llanquihue"),
		("en_US",	"LOC_NAMED_LAKE_OHIGGINS_NAME",					"O’Higgins"),
		("en_US",	"LOC_NAMED_LAKE_RANCO_NAME",					"Ranco Lake"),
		("en_US",	"LOC_NAMED_LAKE_PRESIDENTE_RIOS_NAME",			"Presidente Rios Lake"),
		("en_US",	"LOC_NAMED_LAKE_GREVE_NAME",					"Greve Lake"),
		("en_US",	"LOC_NAMED_LAKE_RUPANCO_NAME",					"Rupanco Lake"),
		("en_US",	"LOC_NAMED_LAKE_DEL_TORO_NAME",					"Del Toro Lake"),
		("en_US",	"LOC_NAMED_LAKE_VILLARRICA_NAME",				"Lake Villarrica"),
		("en_US",	"LOC_NAMED_LAKE_TODOS_NAME",					"Lake Todos los Santos"),
		("en_US",	"LOC_NAMED_SEA_CHILEAN_SEA_NAME",				"Chilean Sea"),
		("en_US",	"LOC_NAMED_RIVER_GUDENA_NAME",					"Gudenå"),
		("en_US",	"LOC_NAMED_RIVER_KONGEAEN_NAME",				"Kongeåen"),
		("en_US",	"LOC_NAMED_RIVER_ODENSE_NAME",					"Odense River"),
		("en_US",	"LOC_NAMED_RIVER_POLEA_NAME",					"Pøleå"),
		("en_US",	"LOC_NAMED_RIVER_VARDE_NAME",					"Varde"),
		("en_US",	"LOC_NAMED_RIVER_SUSA_NAME",					"Suså"),
		("en_US",	"LOC_NAMED_RIVER_VEJLE_NAME",					"Vejle River"),
		("en_US",	"LOC_NAMED_MOUNTAIN_MOLLEHOJ_NAME",				"Møllehøj"),
		("en_US",	"LOC_NAMED_MOUNTAIN_YDING_NAME",				"Yding Skovhøj"),
		("en_US",	"LOC_NAMED_MOUNTAIN_EJER_NAME",					"Ejer Bavnehøj"),
		("en_US",	"LOC_NAMED_MOUNTAIN_LINDBJERG_NAME",			"Lindbjerg"),
		("en_US",	"LOC_NAMED_MOUNTAIN_MARGRETELYST_NAME",			"Margretelyst Sø"),
		("en_US",	"LOC_NAMED_MOUNTAIN_VISTOFTE_NAME",				"Vistofte"),
		("en_US",	"LOC_NAMED_MOUNTAIN_RYTTERKNAEGTEN_NAME",		"Rytterknægten"),
		("en_US",	"LOC_NAMED_MOUNTAIN_HIMMELBJERGET_NAME",		"Himmelbjerget"),
		("en_US",	"LOC_NAMED_MOUNTAIN_ABORREBJERG_NAME",			"Aborrebjerg"),
		("en_US",	"LOC_NAMED_LAKE_ARRESO_NAME",					"Arresø"),
		("en_US",	"LOC_NAMED_LAKE_ESRUM_NAME",					"Lake Esrum"),
		("en_US",	"LOC_NAMED_LAKE_STADIL_NAME",					"Stadil Fjord"),
		("en_US",	"LOC_NAMED_LAKE_MOSSO_NAME",					"Mossø"),
		("en_US",	"LOC_NAMED_LAKE_SALTBAEK_NAME",					"Saltbæk Vig"),
		("en_US",	"LOC_NAMED_LAKE_TISSO_NAME",					"Tissø"),
		("en_US",	"LOC_NAMED_LAKE_FURESO_NAME",					"Furesø"),
		("en_US",	"LOC_NAMED_LAKE_ARRESO_NAME",					"Skanderborg Sø"),
		("en_US",	"LOC_NAMED_SEA_ORESUND_NAME",					"Øresund"),
		("en_US",	"LOC_NAMED_RIVER_KEMIJOKI_NAME",				"Kemijoki River"),
		("en_US",	"LOC_NAMED_RIVER_IIJOKI_NAME",					"Iijoki River"),
		("en_US",	"LOC_NAMED_RIVER_OUNASJOKI_NAME",				"Ounasjoki River"),
		("en_US",	"LOC_NAMED_RIVER_KITINEN_NAME",					"Kitinen River"),
		("en_US",	"LOC_NAMED_RIVER_LUIRO_NAME",					"Luiro River"),
		("en_US",	"LOC_NAMED_RIVER_KYMI_NAME",					"Kymi River"),
		("en_US",	"LOC_NAMED_RIVER_SIMOJOKI_NAME",				"Simojoki River"),
		("en_US",	"LOC_NAMED_MOUNTAIN_KARELIDES_NAME",			"Karelides"),
		("en_US",	"LOC_NAMED_MOUNTAIN_SCANDINADIVAN_NAME",		"Scandinavian Mountains"),
		("en_US",	"LOC_NAMED_VOLCANO_AITOLAHTI_NAME",				"Aitolahti"),
		("en_US",	"LOC_NAMED_LAKE_ROINE_NAME",					"Roine Lake"),
		("en_US",	"LOC_NAMED_LAKE_SAIMAA_NAME",					"Lake Saimaa"),
		("en_US",	"LOC_NAMED_LAKE_PAIJANNE_NAME",					"Lake Päijänne"),
		("en_US",	"LOC_NAMED_LAKE_INARI_NAME",					"Lake Inari"),
		("en_US",	"LOC_NAMED_LAKE_OULUJARVI_NAME",				"Lake Oulujärvi"),
		("en_US",	"LOC_NAMED_LAKE_PIELINEN_NAME",					"Lake Pielinen"),
		("en_US",	"LOC_NAMED_LAKE_PIHLAJAVESI_NAME",				"Lake Pihlajavesi"),
		("en_US",	"LOC_NAMED_LAKE_ORIVESI_NAME",					"Lake Orivesi"),
		("en_US",	"LOC_NAMED_LAKE_HAUKIVESI_NAME",				"Lake Haukivesi"),
		("en_US",	"LOC_NAMED_LAKE_PYHASELKA_NAME",				"Lake Pyhäselkä"),
		("en_US",	"LOC_NAMED_LAKE_PUULA_NAME",					"Lake Puula"),
		("en_US",	"LOC_NAMED_LAKE_HOYTIANEN_NAME",				"Lake Höytiäinen"),
		("en_US",	"LOC_NAMED_SEA_GULF_OF_BOTHNIA_NAME",			"Gulf of Bothnia"),
		("en_US",	"LOC_NAMED_SEA_GULF_OF_FINLAND_NAME",			"Gulf of Finland"),
		("en_US",	"LOC_NAMED_RIVER_THJORSA_NAME",					"Þjórsá River"),
		("en_US",	"LOC_NAMED_RIVER_HVITA_NAME",					"Hvítá River"),
		("en_US",	"LOC_NAMED_RIVER_FNJOSKA_NAME",					"Fnjóská River"),
		("en_US",	"LOC_NAMED_RIVER_KUTHAFLJOT_NAME",				"Kúðafljót River"),
		("en_US",	"LOC_NAMED_RIVER_SKJALFANDAFLJOT_NAME",			"Skjálfandafljót"),
		("en_US",	"LOC_NAMED_RIVER_JOKULSA_A_FJOLLUM_NAME",		"Jökulsá á Fjöllum"),
		("en_US",	"LOC_NAMED_RIVER_JOKULSA_A_DAL_NAME",			"Jökulsá á Dal"),
		("en_US",	"LOC_NAMED_MOUNTAIN_ESJAN_NAME",				"Esjan"),
		("en_US",	"LOC_NAMED_MOUNTAIN_HOFSJOKULL_NAME",			"Hofsjökull"),
		("en_US",	"LOC_NAMED_MOUNTAIN_VATNAJOKULL_NAME",			"Vatnajökull"),
		("en_US",	"LOC_NAMED_MOUNTAIN_LANGJOKULL_NAME",			"Langjökull"),
		("en_US",	"LOC_NAMED_MOUNTAIN_MYRDALSJOKULL_NAME",		"Mýrdalsjökull"),
		("en_US",	"LOC_NAMED_MOUNTAIN_LANDMANNALAUGAR_NAME",		"Landmannalaugar Mountains"),
		("en_US",	"LOC_NAMED_VOLCANO_HEKLA_NAME",					"Hekla Volcano"),
		("en_US",	"LOC_NAMED_VOLCANO_BARTHARBUNGA_NAME",			"Bárðarbunga"),
		("en_US",	"LOC_NAMED_VOLCANO_KATLA_NAME",					"Katla Volcano"),
		("en_US",	"LOC_NAMED_VOLCANO_KRAFLA_CALDERA_NAME",		"Krafla Caldera"),
		("en_US",	"LOC_NAMED_VOLCANO_ASKJA_CALDERA_NAME",			"Askja Caldera"),
		("en_US",	"LOC_NAMED_VOLCANO_ELDFELL_NAME",				"Eldfell Volcano"),
		("en_US",	"LOC_NAMED_VOLCANO_THRIHNJUKAGIGUR_NAME",		"Þríhnjúkagígur"),
		("en_US",	"LOC_NAMED_LAKE_THINGVALLAVATN_NAME",			"Þingvallavatn"),
		("en_US",	"LOC_NAMED_LAKE_MYVATN_NAME",					"Mývatn"),
		("en_US",	"LOC_NAMED_LAKE_KERITH_NAME",					"Kerið"),
		("en_US",	"LOC_NAMED_LAKE_OSKJUVATN_NAME",				"Öskjuvatn"),
		("en_US",	"LOC_NAMED_LAKE_JOKULSARLON_NAME",				"Jökulsárlón"),
		("en_US",	"LOC_NAMED_LAKE_LAGARFLJOT_NAME",				"Lagarfljót"),
		("en_US",	"LOC_NAMED_LAKE_HVITARVATN_NAME",				"Hvítárvatn"),
		("en_US",	"LOC_NAMED_SEA_BAKKAFLOI_NAME",					"Bakkaflói"),
		("en_US",	"LOC_NAMED_SEA_FAXAFLOI_NAME",					"Faxaflói"),
		("en_US",	"LOC_NAMED_SEA_GRUNNAVIK_NAME",					"Grunnavík"),
		("en_US",	"LOC_NAMED_SEA_HERADSFLOI_NAME",				"Héradsflói"),
		("en_US",	"LOC_NAMED_SEA_HUNAFLOI_NAME",					"Húnaflói"),
		("en_US",	"LOC_NAMED_SEA_THISTILFJORTHUR_NAME",			"Þistilfjörður"),
		("en_US",	"LOC_NAMED_SEA_BREITHAFJORTHUR_NAME",			"Breiðafjörður"),
		("en_US",	"LOC_NAMED_SEA_ISAFJARTHARDJUP_NAME",			"Ísafjarðardjúp"),
		("en_US",	"LOC_NAMED_SEA_SKAGAFJORTHUR_NAME",				"Skagafjörður"),
		("en_US",	"LOC_NAMED_SEA_EYJAFJORTHUR_NAME",				"Eyjafjörður"),
		("en_US",	"LOC_NAMED_RIVER_ADIGE_NAME",					"Adige River"),
		("en_US",	"LOC_NAMED_RIVER_OGLIO_NAME",					"Oglio River"),
		("en_US",	"LOC_NAMED_RIVER_PIAVE_NAME",					"Piave River"),
		("en_US",	"LOC_NAMED_RIVER_RENO_NAME",					"Reno River"),
		("en_US",	"LOC_NAMED_RIVER_TAGLIAMENTO_NAME",				"Tagliamento River"),
		("en_US",	"LOC_NAMED_RIVER_TANARO_NAME",					"Tanaro River"),
		("en_US",	"LOC_NAMED_RIVER_MANGOKY_NAME",					"Mangoky River"),
		("en_US",	"LOC_NAMED_RIVER_ONILAHY_NAME",					"Onilahy River"),
		("en_US",	"LOC_NAMED_RIVER_BETSIBOKA_NAME",				"Betsiboka River"),
		("en_US",	"LOC_NAMED_RIVER_MATSIATRA_NAME",				"Matsiatra River"),
		("en_US",	"LOC_NAMED_RIVER_MANAMBOLO_NAME",		        "Manambolo River"),
		("en_US",	"LOC_NAMED_RIVER_MANANANTANANA_NAME",		    "Mananantanana River"),
		("en_US",	"LOC_NAMED_RIVER_IKOSY_NAME",			        "Ikosy River"),
		("en_US",	"LOC_NAMED_MOUNTAIN_TSARATANANA_NAME",			"Massif du Tsaratanana"),
		("en_US",	"LOC_NAMED_MOUNTAIN_ANKARATRA_NAME",			"Ankaratra"),
		("en_US",	"LOC_NAMED_MOUNTAIN_TSIAFAJAVONA_NAME",			"Tsiafajavona"),
		("en_US",	"LOC_NAMED_MOUNTAIN_ANDRINGITRA_NAME",			"Andringitra"),
		("en_US",	"LOC_NAMED_VOLCANO_BOBAOMBY_NAME",				"Ambre-Bobaomby"),
		("en_US",	"LOC_NAMED_VOLCANO_ANKAIZINA_NAME",				"Ankaizina Field"),
		("en_US",	"LOC_NAMED_VOLCANO_ANKARATRA_NAME",				"Ankaratra Field"),
		("en_US",	"LOC_NAMED_VOLCANO_ITASY_NAME",		        	"Itasy Volcano"),
		("en_US",	"LOC_NAMED_VOLCANO_NOSYBE_NAME",		        "Nosy-Be"),
		("en_US",	"LOC_NAMED_LAKE_ALAOTRA_NAME",		        	"Lake Alaotra"),
		("en_US",	"LOC_NAMED_LAKE_KINKONY_NAME",					"Lake Kinkony"),
		("en_US",	"LOC_NAMED_LAKE_TSIMANAPETSOTSOA_NAME",			"Lake Tsimanampetsotsa"),
		("en_US",	"LOC_NAMED_LAKE_ANOSY_NAME",				    "Lake Anosy"),
		("en_US",	"LOC_NAMED_LAKE_IHOTRY_NAME",				    "Lake Ihotry"),
		("en_US",	"LOC_NAMED_RIVER_KLANG_NAME",					"Klang River"),
		("en_US",	"LOC_NAMED_RIVER_PAHANG_NAME",					"Pahang River"),
		("en_US",	"LOC_NAMED_RIVER_PERAK_NAME",					"Perak River"),
		("en_US",	"LOC_NAMED_RIVER_RAJANG_NAME",					"Rajang River"),
		("en_US",	"LOC_NAMED_RIVER_KINABATANGAN_NAME",			"Kinabatangan River"),
		("en_US",	"LOC_NAMED_RIVER_KELANTAN_NAME",				"Kelantan River"),
		("en_US",	"LOC_NAMED_RIVER_OSUN_NAME",					"Osun River"),
		("en_US",	"LOC_NAMED_RIVER_IMO_NAME",						"Imo River"),
		("en_US",	"LOC_NAMED_RIVER_CROSS_NAME",					"Cross River"),
		("en_US",	"LOC_NAMED_RIVER_YOBE_NAME",					"Yobe River"),
		("en_US",	"LOC_NAMED_RIVER_BENUE_NAME",					"Benue River"),
		("en_US",	"LOC_NAMED_RIVER_SOKOTO_NAME",					"Sokoto River"),
		("en_US",	"LOC_NAMED_LAKE_CHAD_NAME",						"Lake Chad"),
		("en_US",	"LOC_NAMED_LAKE_KAINJI_NAME",					"Kainji Lake"),
		("en_US",	"LOC_NAMED_DESERT_KHARAN_NAME",					"Kharan Desert"),
		("en_US",	"LOC_NAMED_DESERT_CHOLISTAN_NAME",				"Cholistan Desert"),
		("en_US",	"LOC_NAMED_RIVER_PASIG_NAME",					"Pasig River"),
		("en_US",	"LOC_NAMED_RIVER_AGUSAN_NAME",					"Agusan River"),
		("en_US",	"LOC_NAMED_RIVER_CAGAYAN_NAME",					"Cagayan River"),
		("en_US",	"LOC_NAMED_RIVER_MINDANAO_NAME",				"Pulangi River"),
		("en_US",	"LOC_NAMED_RIVER_PAMPANGA_NAME",				"Pampanga River"),
		("en_US",	"LOC_NAMED_MOUNTAIN_ZAMBALES_NAME",				"Zambales Mountains"),
		("en_US",	"LOC_NAMED_MOUNTAIN_SIERRA_PHILIPPINES_NAME",	"Sierra Madre"),
		("en_US",	"LOC_NAMED_MOUNTAIN_CARABALLO_NAME",			"Caraballo Mountains"),
		("en_US",	"LOC_NAMED_MOUNTAIN_CORDILLERA_CENTRAL_NAME",	"Cordillera Central"),
		("en_US",	"LOC_NAMED_VOLCANO_MAYON_NAME",					"Mayon"),
		("en_US",	"LOC_NAMED_VOLCANO_PINATUBO_NAME",				"Pinatubo"),
		("en_US",	"LOC_NAMED_VOLCANO_TAAL_NAME",					"Taal"),
		("en_US",	"LOC_NAMED_VOLCANO_BULUSAN_NAME",				"Bulusan"),
		("en_US",	"LOC_NAMED_VOLCANO_KANLAON_NAME",				"Kanlaon"),
		("en_US",	"LOC_NAMED_VOLCANO_HIBOK_HIBOK_NAME",			"Hibok-Hibok"),
		("en_US",	"LOC_NAMED_LAKE_LAGUNA_DE_BAY_NAME",			"Laguna de Bay"),
		("en_US",	"LOC_NAMED_LAKE_LANAO_NAME",					"Lake Lanao"),
		("en_US",	"LOC_NAMED_LAKE_LAIKE_MAINIT_NAME",				"Laike Mainit"),
		("en_US",	"LOC_NAMED_LAKE_NAUJAN_NAME",					"Naujan Lake"),
		("en_US",	"LOC_NAMED_LAKE_BULUAN_NAME",					"Lake Buluan"),
		("en_US",	"LOC_NAMED_LAKE_BATO_NAME",						"Lake Bato"),
		("en_US",	"LOC_NAMED_LAKE_BUHI_NAME",						"Lake Buhi"),
		("en_US",	"LOC_NAMED_SEA_VISAYAN_SEA_NAME",				"Visayan Sea"),
		("en_US",	"LOC_NAMED_SEA_CAMOTES_SEA_NAME",				"Camotes Sea"),
		("en_US",	"LOC_NAMED_SEA_SIBUYAN_SEA_NAME",				"Sibuyan Sea"),
		("en_US",	"LOC_NAMED_SEA_SAMAR_SEA_NAME",					"Samar Sea"),
		("en_US",	"LOC_NAMED_SEA_MORO_GULF_NAME",					"Moro Gulf"),
		("en_US",	"LOC_NAMED_SEA_LEYTE_GULF_NAME",				"Leyte Gulf"),
		("en_US",	"LOC_NAMED_SEA_LINGAYEN_GULF_NAME",				"Lingayen Gulf"),
		("en_US",	"LOC_NAMED_SEA_DAVAO_GULF_NAME",				"Davao Gulf"),
		("en_US",	"LOC_NAMED_SEA_PANAY_GULF_NAME",				"Panay Gulf"),
		("en_US",	"LOC_NAMED_SEA_LUZON_STRAIT_NAME",				"Luzon Strait"),
		("en_US",	"LOC_NAMED_SEA_SIBUTU_PASSAGE_NAME",			"Sibutu Passage"),
		("en_US",	"LOC_NAMED_SEA_MANILA_BAY_NAME",				"Manila Bay"),
		("en_US",	"LOC_NAMED_SEA_BUTUAN_BAY_NAME",				"Butuan Bay"),
		("en_US",	"LOC_NAMED_RIVER_MURES_NAME",					"Mureș River"),
		("en_US",	"LOC_NAMED_RIVER_PRUT_NAME",					"Prut River"),
		("en_US",	"LOC_NAMED_RIVER_OLT_NAME",						"Olt River"),
		("en_US",	"LOC_NAMED_RIVER_SIRET_NAME",					"Siret River"),
		("en_US",	"LOC_NAMED_RIVER_IALOMITA_NAME",				"Ialomița River"),
		("en_US",	"LOC_NAMED_RIVER_SOMES_NAME",					"Someș River"),
		("en_US",	"LOC_NAMED_RIVER_ARGES_NAME",					"Argeș River"),
		("en_US",	"LOC_NAMED_RIVER_JIU_NAME",						"Jiu River"),
		("en_US",	"LOC_NAMED_RIVER_BUZAU_NAME",					"Buzău River"),
		("en_US",	"LOC_NAMED_RIVER_DAMBOVITA_NAME",				"Dâmbovița River"),
		("en_US",	"LOC_NAMED_MOUNTAIN_ALMAJ_NAME",		 		"Almăj Mountains"),
		("en_US",	"LOC_NAMED_MOUNTAIN_BIHOR_NAME",				"Bihor Mountains"),
		("en_US",	"LOC_NAMED_MOUNTAIN_BUCEGI_NAME",				"Bucegi Mountains"),
		("en_US",	"LOC_NAMED_MOUNTAIN_FAGARAS_NAME",				"Făgăraş Mountains"),
		("en_US",	"LOC_NAMED_MOUNTAIN_GODEANU_NAME",				"Godeanu Mountains"),
		("en_US",	"LOC_NAMED_MOUNTAIN_RETEZAT_NAME",	 			"Retezat Mountains"),
		("en_US",	"LOC_NAMED_MOUNTAIN_VRANCEA_NAME",	 			"Vrancea Mountains"),
		("en_US",	"LOC_NAMED_MOUNTAIN_SUREANU_NAME",	 			"Şureanu Mountains"),
		("en_US",	"LOC_NAMED_MOUNTAIN_TARCU_NAME",		 		"Ţarcu Mountains"),
		("en_US",	"LOC_NAMED_VOLCANO_CIOMADUL_NAME",				"Ciomadul"),
		("en_US",	"LOC_NAMED_LAKE_BALEA_NAME",					"Lacul Bâlea"),
		("en_US",	"LOC_NAMED_LAKE_RAZIM_NAME",					"Lacul Razim"),
		("en_US",	"LOC_NAMED_LAKE_ROSU_NAME",						"Lacul Roşu"),
		("en_US",	"LOC_NAMED_LAKE_TAUL_TAPULUI_NAME",				"Tăul Țapului"),
		("en_US",	"LOC_NAMED_RIVER_CHAO_PHRAYA_NAME",				"Chao Phraya River"),
		("en_US",	"LOC_NAMED_RIVER_PING_NAME",					"Ping River"),
		("en_US",	"LOC_NAMED_RIVER_NAN_NAME",						"Nan River"),
		("en_US",	"LOC_NAMED_RIVER_WANG_NAME",					"Wang River"),
		("en_US",	"LOC_NAMED_RIVER_YOM_NAME",						"Yom River"),
		("en_US",	"LOC_NAMED_RIVER_PA_SAK_NAME",					"Pa Sak River"),
		("en_US",	"LOC_NAMED_RIVER_MUN_NAME",						"Mun River"),
		("en_US",	"LOC_NAMED_MOUNTAIN_DAEN_LAO_NAME",				"Daen Lao Range"),
		("en_US",	"LOC_NAMED_MOUNTAIN_LUANG_PRABANG_NAME",		"Luang Prabang Range"),
		("en_US",	"LOC_NAMED_MOUNTAIN_THANON_THONG_CHAI_NAME",	"Thanon Thong Chai Range"),
		("en_US",	"LOC_NAMED_MOUNTAIN_PHI_PAN_NAM_NAME",			"Phi Pan Nam Range"),
		("en_US",	"LOC_NAMED_MOUNTAIN_PETCHABUN_NAME",			"Petchabun Mountains"),
		("en_US",	"LOC_NAMED_MOUNTAIN_SANKHAMPHAENG_NAME",		"Sankhamphaeng Range"),
		("en_US",	"LOC_NAMED_MOUNTAIN_BANTHAT_NAME",				"Banthat Range"),
		("en_US",	"LOC_NAMED_MOUNTAIN_SANKALAKHIRI_NAME",			"Sankalakhiri Range"),
		("en_US",	"LOC_NAMED_MOUNTAIN_TENASSERIM_NAME",			"Tenasserim Range"),
		("en_US",	"LOC_NAMED_VOLCANO_DOI_PHA_KHOK_HIN_FUU_NAME",	"Doi Pha Khok Hin Fuu"),
		("en_US",	"LOC_NAMED_LAKE_BUENG_BORAPHET_NAME",		    "Bueng Boraphet"),
		("en_US",	"LOC_NAMED_LAKE_SONGKHLA_NAME",			    	"Songkhla Lake"),
		("en_US",	"LOC_NAMED_LAKE_PHAYAO_NAME",				    "Phayao Lake"),
		("en_US",	"LOC_NAMED_LAKE_NONG_HAN_NAME",			    	"Nong Han"),
		("en_US",	"LOC_NAMED_SEA_KRUNG_THEP_BAY_NAME",		    "Krung Thep Bay"),
		("en_US",	"LOC_NAMED_SEA_PHANG_NGA_BAY_NAME",		    	"Phang Nga Bay"),
		("en_US",	"LOC_NAMED_SEA_PRACHUAP_BAY_NAME",			    "Prachuap Bay"),
		("en_US",	"LOC_NAMED_SEA_SATTAHIP_BAY_NAME",			    "Sattahip Bay"),
		("en_US",	"LOC_NAMED_SEA_BANDON_BAY_NAME",			    "Bandon Bay"),
		("en_US",	"LOC_NAMED_SEA_MANAO_BAY_NAME",			    	"Manao Bay");