/*
	Civilopedia Text
	Authors: GameBoy2936
*/

INSERT INTO LocalizedText
			(Language, Tag, Text)
VALUES

	("en_US",	"LOC_CIVINFO_LANGUAGE",
	"Majority Language(s)"),
	("en_US",	"LOC_CIVINFO_RELIGION",
	"Majority Religion(s)"),
	
-- Geographical and Social Statistics
	("en_US",	"LOC_CIVINFO_ALGERIA_LOCATION",
	"Northern Africa"),
	("en_US",	"LOC_CIVINFO_ALGERIA_SIZE",
	"919,595 square miles (2,381,741 square km)"),
	("en_US",	"LOC_CIVINFO_ALGERIA_POPULATION",
	"45,242,330 (in 2022)"),
	("en_US",	"LOC_CIVINFO_ALGERIA_CAPITAL",
	"Algiers"),
	("en_US",	"LOC_CIVINFO_ALGERIA_LANGUAGE",
	"Arabic and French"),
	("en_US",	"LOC_CIVINFO_ALGERIA_RELIGION",
	"Islam"),
	("en_US",	"LOC_CIVINFO_AMERICA_LOCATION",
	"North America"),
	("en_US",	"LOC_CIVINFO_AMERICA_SIZE",
	"3,618,783 square miles (9,372,610 square km)"),
	("en_US",	"LOC_CIVINFO_AMERICA_POPULATION",
	"339,035,004 (in 2022)"),
	("en_US",	"LOC_CIVINFO_AMERICA_CAPITAL",
	"Washington D.C."),
	("en_US",	"LOC_CIVINFO_AMERICA_LANGUAGE",
	"English"),
	("en_US",	"LOC_CIVINFO_AMERICA_RELIGION",
	"Christianity"),
	("en_US",	"LOC_CIVINFO_ANGOLA_LOCATION",
	"Central Africa"),
	("en_US",	"LOC_CIVINFO_ANGOLA_SIZE",
	"481,353 square miles (1,246,700 square km)"),
	("en_US",	"LOC_CIVINFO_ANGOLA_POPULATION",
	"36,097,646 (in 2022)"),
	("en_US",	"LOC_CIVINFO_ANGOLA_CAPITAL",
	"Luanda"),
	("en_US",	"LOC_CIVINFO_ANGOLA_LANGUAGE",
	"Portuguese and Kimbundu"),
	("en_US",	"LOC_CIVINFO_ANGOLA_RELIGION",
	"Christianity"),
	("en_US",	"LOC_CIVINFO_ARABIA_LOCATION",
	"Middle-East"),
	("en_US",	"LOC_CIVINFO_ARABIA_SIZE",
	"830,000 square miles (2,149,690 square km)"),
	("en_US",	"LOC_CIVINFO_ARABIA_POPULATION",
	"36,666,128 (in 2022)"),
	("en_US",	"LOC_CIVINFO_ARABIA_CAPITAL",
	"Riyadh"),
	("en_US",	"LOC_CIVINFO_ARABIA_LANGUAGE",
	"Arabic"),
	("en_US",	"LOC_CIVINFO_ARABIA_RELIGION",
	"Islam"),
	("en_US",	"LOC_CIVINFO_ARGENTINA_LOCATION",
	"South America"),
	("en_US",	"LOC_CIVINFO_ARGENTINA_SIZE",
	"1,073,518 square miles (2,780,400 square km)"),
	("en_US",	"LOC_CIVINFO_ARGENTINA_POPULATION",
	"45,623,355 (in 2022)"),
	("en_US",	"LOC_CIVINFO_ARGENTINA_CAPITAL",
	"Buenos Aires"),
	("en_US",	"LOC_CIVINFO_ARGENTINA_LANGUAGE",
	"Spanish"),
	("en_US",	"LOC_CIVINFO_ARGENTINA_RELIGION",
	"Christianity"),
	("en_US",	"LOC_CIVINFO_AUSTRALIA_LOCATION",
	"Oceania"),
	("en_US",	"LOC_CIVINFO_AUSTRALIA_SIZE",
	"2,969,906 square miles (7,692,024 square km)"),
	("en_US",	"LOC_CIVINFO_AUSTRALIA_POPULATION",
	"26,300,862 (in 2022)"),
	("en_US",	"LOC_CIVINFO_AUSTRALIA_CAPITAL",
	"Canberra"),
	("en_US",	"LOC_CIVINFO_AUSTRALIA_LANGUAGE",
	"English"),
	("en_US",	"LOC_CIVINFO_AUSTRALIA_RELIGION",
	"Christianity"),
	("en_US",	"LOC_CIVINFO_BRAZIL_LOCATION",
	"South America"),
	("en_US",	"LOC_CIVINFO_BRAZIL_SIZE",
	"3,287,955 square miles (8,515,767 square km)"),
	("en_US",	"LOC_CIVINFO_BRAZIL_POPULATION",
	"215,774,574 (in 2022)"),
	("en_US",	"LOC_CIVINFO_BRAZIL_CAPITAL",
	"Brasília"),
	("en_US",	"LOC_CIVINFO_BRAZIL_LANGUAGE",
	"Portuguese"),
	("en_US",	"LOC_CIVINFO_BRAZIL_RELIGION",
	"Christianity"),
	("en_US",	"LOC_CIVINFO_CANADA_LOCATION",
	"North America"),
	("en_US",	"LOC_CIVINFO_CANADA_SIZE",
	"3,855,101 square miles (9,984,670 square km)"),
	("en_US",	"LOC_CIVINFO_CANADA_POPULATION",
	"38,609,013 (in 2022)"),
	("en_US",	"LOC_CIVINFO_CANADA_CAPITAL",
	"Ottawa"),
	("en_US",	"LOC_CIVINFO_CANADA_LANGUAGE",
	"English"),
	("en_US",	"LOC_CIVINFO_CANADA_RELIGION",
	"Christianity"),
	("en_US",	"LOC_CIVINFO_CHILE_LOCATION",
	"South America"),
	("en_US",	"LOC_CIVINFO_CHILE_SIZE",
	"291,932 square miles (756,102 square km)"),
	("en_US",	"LOC_CIVINFO_CHILE_POPULATION",
	"19,614,145 (in 2022)"),
	("en_US",	"LOC_CIVINFO_CHILE_CAPITAL",
	"Santiago"),
	("en_US",	"LOC_CIVINFO_CHILE_LANGUAGE",
	"Spanish"),
	("en_US",	"LOC_CIVINFO_CHILE_RELIGION",
	"Christianity"),
	("en_US",	"LOC_CIVINFO_CHINA_PRC_LOCATION",
	"East Asia"),
	("en_US",	"LOC_CIVINFO_CHINA_PRC_SIZE",
	"3,747,877 square miles (9,706,961 square km)"),
	("en_US",	"LOC_CIVINFO_CHINA_PRC_POPULATION",
	"1,425,851,640 (in 2022)"),
	("en_US",	"LOC_CIVINFO_CHINA_PRC_CAPITAL",
	"Beijing"),
	("en_US",	"LOC_CIVINFO_CHINA_PRC_LANGUAGE",
	"Chinese"),
	("en_US",	"LOC_CIVINFO_CHINA_PRC_RELIGION",
	"Buddhism, Confucianism and Taoism"),
	("en_US",	"LOC_CIVINFO_CHINA_ROC_LOCATION",
	"East Asia"),
	("en_US",	"LOC_CIVINFO_CHINA_ROC_SIZE",
	"13,974 square miles (36,193 square km)"),
	("en_US",	"LOC_CIVINFO_CHINA_ROC_POPULATION",
	"23,908,268 (in 2022)"),
	("en_US",	"LOC_CIVINFO_CHINA_ROC_CAPITAL",
	"Taipei"),
	("en_US",	"LOC_CIVINFO_CHINA_ROC_LANGUAGE",
	"Chinese"),
	("en_US",	"LOC_CIVINFO_CHINA_ROC_RELIGION",
	"Buddhism and Taoism"),
	("en_US",	"LOC_CIVINFO_COLOMBIA_LOCATION",
	"South America"),
	("en_US",	"LOC_CIVINFO_COLOMBIA_SIZE",
	"440,831 square miles (1,141,748 square km)"),
	("en_US",	"LOC_CIVINFO_COLOMBIA_POPULATION",
	"51,954,345 (in 2022)"),
	("en_US",	"LOC_CIVINFO_COLOMBIA_CAPITAL",
	"Bogotá"),
	("en_US",	"LOC_CIVINFO_COLOMBIA_LANGUAGE",
	"Spanish"),
	("en_US",	"LOC_CIVINFO_COLOMBIA_RELIGION",
	"Christianity"),
	("en_US",	"LOC_CIVINFO_CONGO_LOCATION",
	"Central Africa"),
	("en_US",	"LOC_CIVINFO_CONGO_SIZE",
	"132,047 square miles (342,000 square km)"),
	("en_US",	"LOC_CIVINFO_CONGO_POPULATION",
	"100,515,502 (in 2022)"),
	("en_US",	"LOC_CIVINFO_CONGO_CAPITAL",
	"Kinshasa"),
	("en_US",	"LOC_CIVINFO_CONGO_LANGUAGE",
	"French, Kikongo and Lingala"),
	("en_US",	"LOC_CIVINFO_CONGO_RELIGION",
	"Christianity"),
	("en_US",	"LOC_CIVINFO_CUBA_LOCATION",
	"Caribbean (Central America)"),
	("en_US",	"LOC_CIVINFO_CUBA_SIZE",
	"42,426 square miles (109,884 square km)"),
	("en_US",	"LOC_CIVINFO_CUBA_POPULATION",
	"11,204,754 (in 2022)"),
	("en_US",	"LOC_CIVINFO_CUBA_CAPITAL",
	"Havana"),
	("en_US",	"LOC_CIVINFO_CUBA_LANGUAGE",
	"Spanish"),
	("en_US",	"LOC_CIVINFO_CUBA_RELIGION",
	"Christianity"),
	("en_US",	"LOC_CIVINFO_DENMARK_LOCATION",
	"Scandinavia (Northern Europe)"),
	("en_US",	"LOC_CIVINFO_DENMARK_SIZE",
	"16,639 square miles (43,094 square km)"),
	("en_US",	"LOC_CIVINFO_DENMARK_POPULATION",
	"5,895,648 (in 2022)"),
	("en_US",	"LOC_CIVINFO_DENMARK_CAPITAL",
	"Copenhagen"),
	("en_US",	"LOC_CIVINFO_DENMARK_LANGUAGE",
	"Danish"),
	("en_US",	"LOC_CIVINFO_DENMARK_RELIGION",
	"Christianity"),
	("en_US",	"LOC_CIVINFO_EGYPT_LOCATION",
	"Northern Africa"),
	("en_US",	"LOC_CIVINFO_EGYPT_SIZE",
	"___ square miles (___ square km)"),
	("en_US",	"LOC_CIVINFO_EGYPT_POPULATION",
	"___ (in 2022)"),
	("en_US",	"LOC_CIVINFO_EGYPT_CAPITAL",
	"___"),
	("en_US",	"LOC_CIVINFO_EGYPT_LANGUAGE",
	"___"),
	("en_US",	"LOC_CIVINFO_EGYPT_RELIGION",
	"___"),
	("en_US",	"LOC_CIVINFO_ETHIOPIA_LOCATION",
	"East Africa"),
	("en_US",	"LOC_CIVINFO_ETHIOPIA_SIZE",
	"___ square miles (___ square km)"),
	("en_US",	"LOC_CIVINFO_ETHIOPIA_POPULATION",
	"___ (in 2022)"),
	("en_US",	"LOC_CIVINFO_ETHIOPIA_CAPITAL",
	"___"),
	("en_US",	"LOC_CIVINFO_ETHIOPIA_LANGUAGE",
	"___"),
	("en_US",	"LOC_CIVINFO_ETHIOPIA_RELIGION",
	"___"),
	("en_US",	"LOC_CIVINFO_FINLAND_LOCATION",
	"Scandinavia (Northern Europe)"),
	("en_US",	"LOC_CIVINFO_FINLAND_SIZE",
	"___ square miles (___ square km)"),
	("en_US",	"LOC_CIVINFO_FINLAND_POPULATION",
	"___ (in 2022)"),
	("en_US",	"LOC_CIVINFO_FINLAND_CAPITAL",
	"___"),
	("en_US",	"LOC_CIVINFO_FINLAND_LANGUAGE",
	"___"),
	("en_US",	"LOC_CIVINFO_FINLAND_RELIGION",
	"___"),
	("en_US",	"LOC_CIVINFO_FRANCE_LOCATION",
	"West Europe"),
	("en_US",	"LOC_CIVINFO_FRANCE_SIZE",
	"___ square miles (___ square km)"),
	("en_US",	"LOC_CIVINFO_FRANCE_POPULATION",
	"___ (in 2022)"),
	("en_US",	"LOC_CIVINFO_FRANCE_CAPITAL",
	"___"),
	("en_US",	"LOC_CIVINFO_FRANCE_LANGUAGE",
	"___"),
	("en_US",	"LOC_CIVINFO_FRANCE_RELIGION",
	"___"),
	("en_US",	"LOC_CIVINFO_GERMANY_LOCATION",
	"West Europe"),
	("en_US",	"LOC_CIVINFO_GERMANY_SIZE",
	"___ square miles (___ square km)"),
	("en_US",	"LOC_CIVINFO_GERMANY_POPULATION",
	"___ (in 2022)"),
	("en_US",	"LOC_CIVINFO_GERMANY_CAPITAL",
	"___"),
	("en_US",	"LOC_CIVINFO_GERMANY_LANGUAGE",
	"___"),
	("en_US",	"LOC_CIVINFO_GERMANY_RELIGION",
	"___"),
	("en_US",	"LOC_CIVINFO_GREECE_LOCATION",
	"Southern Europe"),
	("en_US",	"LOC_CIVINFO_GREECE_SIZE",
	"___ square miles (___ square km)"),
	("en_US",	"LOC_CIVINFO_GREECE_POPULATION",
	"___ (in 2022)"),
	("en_US",	"LOC_CIVINFO_GREECE_CAPITAL",
	"___"),
	("en_US",	"LOC_CIVINFO_GREECE_LANGUAGE",
	"___"),
	("en_US",	"LOC_CIVINFO_GREECE_RELIGION",
	"___"),
	("en_US",	"LOC_CIVINFO_ICELAND_LOCATION",
	"Scandinavia (Northern Europe)"),
	("en_US",	"LOC_CIVINFO_ICELAND_SIZE",
	"39,769 thousand square miles (103,000 thousand square km)"),
	("en_US",	"LOC_CIVINFO_ICELAND_POPULATION",
	"374,380 (in 2022)"),
	("en_US",	"LOC_CIVINFO_ICELAND_CAPITAL",
	"Reykjavík"),
	("en_US",	"LOC_CIVINFO_ICELAND_LANGUAGE",
	"Icelandic"),
	("en_US",	"LOC_CIVINFO_ICELAND_RELIGION",
	"Christianity"),
	("en_US",	"LOC_CIVINFO_INDIA_LOCATION",
	"South Asia"),
	("en_US",	"LOC_CIVINFO_INDIA_SIZE",
	"___ square miles (___ square km)"),
	("en_US",	"LOC_CIVINFO_INDIA_POPULATION",
	"___ (in 2022)"),
	("en_US",	"LOC_CIVINFO_INDIA_CAPITAL",
	"___"),
	("en_US",	"LOC_CIVINFO_INDIA_LANGUAGE",
	"___"),
	("en_US",	"LOC_CIVINFO_INDIA_RELIGION",
	"___"),
	("en_US",	"LOC_CIVINFO_INDONESIA_LOCATION",
	"South-East Asia"),
	("en_US",	"LOC_CIVINFO_INDONESIA_SIZE",
	"___ square miles (___ square km)"),
	("en_US",	"LOC_CIVINFO_INDONESIA_POPULATION",
	"___ (in 2022)"),
	("en_US",	"LOC_CIVINFO_INDONESIA_CAPITAL",
	"___"),
	("en_US",	"LOC_CIVINFO_INDONESIA_LANGUAGE",
	"___"),
	("en_US",	"LOC_CIVINFO_INDONESIA_RELIGION",
	"___"),
	("en_US",	"LOC_CIVINFO_IRAN_LOCATION",
	"Middle-East"),
	("en_US",	"LOC_CIVINFO_IRAN_SIZE",
	"___ square miles (___ square km)"),
	("en_US",	"LOC_CIVINFO_IRAN_POPULATION",
	"___ (in 2022)"),
	("en_US",	"LOC_CIVINFO_IRAN_CAPITAL",
	"___"),
	("en_US",	"LOC_CIVINFO_IRAN_LANGUAGE",
	"___"),
	("en_US",	"LOC_CIVINFO_IRAN_RELIGION",
	"___"),
	("en_US",	"LOC_CIVINFO_IRAQ_LOCATION",
	"Middle-East"),
	("en_US",	"LOC_CIVINFO_IRAQ_SIZE",
	"___ square miles (___ square km)"),
	("en_US",	"LOC_CIVINFO_IRAQ_POPULATION",
	"___ (in 2022)"),
	("en_US",	"LOC_CIVINFO_IRAQ_CAPITAL",
	"___"),
	("en_US",	"LOC_CIVINFO_IRAQ_LANGUAGE",
	"___"),
	("en_US",	"LOC_CIVINFO_IRAQ_RELIGION",
	"___"),
	("en_US",	"LOC_CIVINFO_IRELAND_LOCATION",
	"West Europe"),
	("en_US",	"LOC_CIVINFO_IRELAND_SIZE",
	"___ square miles (___ square km)"),
	("en_US",	"LOC_CIVINFO_IRELAND_POPULATION",
	"___ (in 2022)"),
	("en_US",	"LOC_CIVINFO_IRELAND_CAPITAL",
	"___"),
	("en_US",	"LOC_CIVINFO_IRELAND_LANGUAGE",
	"___"),
	("en_US",	"LOC_CIVINFO_IRELAND_RELIGION",
	"___"),
	("en_US",	"LOC_CIVINFO_ISRAEL_LOCATION",
	"Middle-East"),
	("en_US",	"LOC_CIVINFO_ISRAEL_SIZE",
	"___ square miles (___ square km)"),
	("en_US",	"LOC_CIVINFO_ISRAEL_POPULATION",
	"___ (in 2022)"),
	("en_US",	"LOC_CIVINFO_ISRAEL_CAPITAL",
	"___"),
	("en_US",	"LOC_CIVINFO_ISRAEL_LANGUAGE",
	"___"),
	("en_US",	"LOC_CIVINFO_ISRAEL_RELIGION",
	"___"),
	("en_US",	"LOC_CIVINFO_ITALY_LOCATION",
	"Southern Europe"),
	("en_US",	"LOC_CIVINFO_ITALY_SIZE",
	"___ square miles (___ square km)"),
	("en_US",	"LOC_CIVINFO_ITALY_POPULATION",
	"___ (in 2022)"),
	("en_US",	"LOC_CIVINFO_ITALY_CAPITAL",
	"___"),
	("en_US",	"LOC_CIVINFO_ITALY_LANGUAGE",
	"___"),
	("en_US",	"LOC_CIVINFO_ITALY_RELIGION",
	"___"),
	("en_US",	"LOC_CIVINFO_JAPAN_LOCATION",
	"East Asia"),
	("en_US",	"LOC_CIVINFO_JAPAN_SIZE",
	"___ square miles (___ square km)"),
	("en_US",	"LOC_CIVINFO_JAPAN_POPULATION",
	"___ (in 2022)"),
	("en_US",	"LOC_CIVINFO_JAPAN_CAPITAL",
	"___"),
	("en_US",	"LOC_CIVINFO_JAPAN_LANGUAGE",
	"___"),
	("en_US",	"LOC_CIVINFO_JAPAN_RELIGION",
	"___"),
	("en_US",	"LOC_CIVINFO_KAZAKHSTAN_LOCATION",
	"Central Asia"),
	("en_US",	"LOC_CIVINFO_KAZAKHSTAN_SIZE",
	"___ square miles (___ square km)"),
	("en_US",	"LOC_CIVINFO_KAZAKHSTAN_POPULATION",
	"___ (in 2022)"),
	("en_US",	"LOC_CIVINFO_KAZAKHSTAN_CAPITAL",
	"___"),
	("en_US",	"LOC_CIVINFO_KAZAKHSTAN_LANGUAGE",
	"___"),
	("en_US",	"LOC_CIVINFO_KAZAKHSTAN_RELIGION",
	"___"),
	("en_US",	"LOC_CIVINFO_KENYA_LOCATION",
	"East Africa"),
	("en_US",	"LOC_CIVINFO_KENYA_SIZE",
	"___ square miles (___ square km)"),
	("en_US",	"LOC_CIVINFO_KENYA_POPULATION",
	"___ (in 2022)"),
	("en_US",	"LOC_CIVINFO_KENYA_CAPITAL",
	"___"),
	("en_US",	"LOC_CIVINFO_KENYA_LANGUAGE",
	"___"),
	("en_US",	"LOC_CIVINFO_KENYA_RELIGION",
	"___"),
	("en_US",	"LOC_CIVINFO_LIBYA_LOCATION",
	"Northern Africa"),
	("en_US",	"LOC_CIVINFO_LIBYA_SIZE",
	"___ square miles (___ square km)"),
	("en_US",	"LOC_CIVINFO_LIBYA_POPULATION",
	"___ (in 2022)"),
	("en_US",	"LOC_CIVINFO_LIBYA_CAPITAL",
	"___"),
	("en_US",	"LOC_CIVINFO_LIBYA_LANGUAGE",
	"___"),
	("en_US",	"LOC_CIVINFO_LIBYA_RELIGION",
	"___"),
	("en_US",	"LOC_CIVINFO_MADAGASCAR_LOCATION",
	"South-East Africa (Indian Ocean)"),
	("en_US",	"LOC_CIVINFO_MADAGASCAR_SIZE",
	"226,658 square miles (587,041 square km"),
	("en_US",	"LOC_CIVINFO_MADAGASCAR_POPULATION",
	"29,943,392 (in 2022)"),
	("en_US",	"LOC_CIVINFO_MADAGASCAR_CAPITAL",
	"Antananarivo"),
	("en_US",	"LOC_CIVINFO_MADAGASCAR_LANGUAGE",
	"Malagasy and French"),
	("en_US",	"LOC_CIVINFO_MADAGASCAR_RELIGION",
	"Christianity"),
	("en_US",	"LOC_CIVINFO_MALAYSIA_LOCATION",
	"South-East Asia"),
	("en_US",	"LOC_CIVINFO_MALAYSIA_SIZE",
	"127,724 square miles (330,803 square km)"),
	("en_US",	"LOC_CIVINFO_MALAYSIA_POPULATION",
	"34,113,728 (in 2022)"),
	("en_US",	"LOC_CIVINFO_MALAYSIA_CAPITAL",
	"Kuala Lumpur"),
	("en_US",	"LOC_CIVINFO_MALAYSIA_LANGUAGE",
	"Malay"),
	("en_US",	"LOC_CIVINFO_MALAYSIA_RELIGION",
	"Islam"),
	("en_US",	"LOC_CIVINFO_MALI_LOCATION",
	"West Africa"),
	("en_US",	"LOC_CIVINFO_MALI_SIZE",
	"___ square miles (___ square km)"),
	("en_US",	"LOC_CIVINFO_MALI_POPULATION",
	"___ (in 2022)"),
	("en_US",	"LOC_CIVINFO_MALI_CAPITAL",
	"___"),
	("en_US",	"LOC_CIVINFO_MALI_LANGUAGE",
	"___"),
	("en_US",	"LOC_CIVINFO_MALI_RELIGION",
	"___"),
	("en_US",	"LOC_CIVINFO_MEXICO_LOCATION",
	"Central America"),
	("en_US",	"LOC_CIVINFO_MEXICO_SIZE",
	"___ square miles (___ square km)"),
	("en_US",	"LOC_CIVINFO_MEXICO_POPULATION",
	"___ (in 2022)"),
	("en_US",	"LOC_CIVINFO_MEXICO_CAPITAL",
	"___"),
	("en_US",	"LOC_CIVINFO_MEXICO_LANGUAGE",
	"___"),
	("en_US",	"LOC_CIVINFO_MEXICO_RELIGION",
	"___"),
	("en_US",	"LOC_CIVINFO_MONGOLIA_LOCATION",
	"East Asia"),
	("en_US",	"LOC_CIVINFO_MONGOLIA_SIZE",
	"___ square miles (___ square km)"),
	("en_US",	"LOC_CIVINFO_MONGOLIA_POPULATION",
	"___ (in 2022)"),
	("en_US",	"LOC_CIVINFO_MONGOLIA_CAPITAL",
	"___"),
	("en_US",	"LOC_CIVINFO_MONGOLIA_LANGUAGE",
	"___"),
	("en_US",	"LOC_CIVINFO_MONGOLIA_RELIGION",
	"___"),
	("en_US",	"LOC_CIVINFO_MOROCCO_LOCATION",
	"Northern Africa"),
	("en_US",	"LOC_CIVINFO_MOROCCO_SIZE",
	"___ square miles (___ square km)"),
	("en_US",	"LOC_CIVINFO_MOROCCO_POPULATION",
	"___ (in 2022)"),
	("en_US",	"LOC_CIVINFO_MOROCCO_CAPITAL",
	"___"),
	("en_US",	"LOC_CIVINFO_MOROCCO_LANGUAGE",
	"___"),
	("en_US",	"LOC_CIVINFO_MOROCCO_RELIGION",
	"___"),
	("en_US",	"LOC_CIVINFO_MYANMAR_LOCATION",
	"South-East Asia"),
	("en_US",	"LOC_CIVINFO_MYANMAR_SIZE",
	"___ square miles (___ square km)"),
	("en_US",	"LOC_CIVINFO_MYANMAR_POPULATION",
	"___ (in 2022)"),
	("en_US",	"LOC_CIVINFO_MYANMAR_CAPITAL",
	"___"),
	("en_US",	"LOC_CIVINFO_MYANMAR_LANGUAGE",
	"___"),
	("en_US",	"LOC_CIVINFO_MYANMAR_RELIGION",
	"___"),
	("en_US",	"LOC_CIVINFO_NETHERLANDS_LOCATION",
	"West Europe"),
	("en_US",	"LOC_CIVINFO_NETHERLANDS_SIZE",
	"___ square miles (___ square km)"),
	("en_US",	"LOC_CIVINFO_NETHERLANDS_POPULATION",
	"___ (in 2022)"),
	("en_US",	"LOC_CIVINFO_NETHERLANDS_CAPITAL",
	"___"),
	("en_US",	"LOC_CIVINFO_NETHERLANDS_LANGUAGE",
	"___"),
	("en_US",	"LOC_CIVINFO_NETHERLANDS_RELIGION",
	"___"),
	("en_US",	"LOC_CIVINFO_NEW_ZEALAND_LOCATION",
	"Oceania"),
	("en_US",	"LOC_CIVINFO_NEW_ZEALAND_SIZE",
	"___ square miles (___ square km)"),
	("en_US",	"LOC_CIVINFO_NEW_ZEALAND_POPULATION",
	"___ (in 2022)"),
	("en_US",	"LOC_CIVINFO_NEW_ZEALAND_CAPITAL",
	"___"),
	("en_US",	"LOC_CIVINFO_NEW_ZEALAND_LANGUAGE",
	"___"),
	("en_US",	"LOC_CIVINFO_NEW_ZEALAND_RELIGION",
	"___"),
	("en_US",	"LOC_CIVINFO_NIGERIA_LOCATION",
	"West Africa"),
	("en_US",	"LOC_CIVINFO_NIGERIA_SIZE",
	"___ square miles (___ square km)"),
	("en_US",	"LOC_CIVINFO_NIGERIA_POPULATION",
	"___ (in 2022)"),
	("en_US",	"LOC_CIVINFO_NIGERIA_CAPITAL",
	"___"),
	("en_US",	"LOC_CIVINFO_NIGERIA_LANGUAGE",
	"___"),
	("en_US",	"LOC_CIVINFO_NIGERIA_RELIGION",
	"___"),
	("en_US",	"LOC_CIVINFO_NORTH_KOREA_LOCATION",
	"East Asia"),
	("en_US",	"LOC_CIVINFO_NORTH_KOREA_SIZE",
	"___ square miles (___ square km)"),
	("en_US",	"LOC_CIVINFO_NORTH_KOREA_POPULATION",
	"___ (in 2022)"),
	("en_US",	"LOC_CIVINFO_NORTH_KOREA_CAPITAL",
	"___"),
	("en_US",	"LOC_CIVINFO_NORTH_KOREA_LANGUAGE",
	"___"),
	("en_US",	"LOC_CIVINFO_NORTH_KOREA_RELIGION",
	"___"),
	("en_US",	"LOC_CIVINFO_NORWAY_LOCATION",
	"Scandinavia (Northern Europe)"),
	("en_US",	"LOC_CIVINFO_NORWAY_SIZE",
	"___ square miles (___ square km)"),
	("en_US",	"LOC_CIVINFO_NORWAY_POPULATION",
	"___ (in 2022)"),
	("en_US",	"LOC_CIVINFO_NORWAY_CAPITAL",
	"___"),
	("en_US",	"LOC_CIVINFO_NORWAY_LANGUAGE",
	"___"),
	("en_US",	"LOC_CIVINFO_NORWAY_RELIGION",
	"___"),
	("en_US",	"LOC_CIVINFO_PAKISTAN_LOCATION",
	"South Asia"),
	("en_US",	"LOC_CIVINFO_PAKISTAN_SIZE",
	"___ square miles (___ square km)"),
	("en_US",	"LOC_CIVINFO_PAKISTAN_POPULATION",
	"___ (in 2022)"),
	("en_US",	"LOC_CIVINFO_PAKISTAN_CAPITAL",
	"___"),
	("en_US",	"LOC_CIVINFO_PAKISTAN_LANGUAGE",
	"___"),
	("en_US",	"LOC_CIVINFO_PAKISTAN_RELIGION",
	"___"),
	("en_US",	"LOC_CIVINFO_PAPUA_NEW_GUINEA_LOCATION",
	"Oceania"),
	("en_US",	"LOC_CIVINFO_PAPUA_NEW_GUINEA_SIZE",
	"___ square miles (___ square km)"),
	("en_US",	"LOC_CIVINFO_PAPUA_NEW_GUINEA_POPULATION",
	"___ (in 2022)"),
	("en_US",	"LOC_CIVINFO_PAPUA_NEW_GUINEA_CAPITAL",
	"___"),
	("en_US",	"LOC_CIVINFO_PAPUA_NEW_GUINEA_LANGUAGE",
	"___"),
	("en_US",	"LOC_CIVINFO_PAPUA_NEW_GUINEA_RELIGION",
	"___"),
	("en_US",	"LOC_CIVINFO_PERU_LOCATION",
	"South America"),
	("en_US",	"LOC_CIVINFO_PERU_SIZE",
	"___ square miles (___ square km)"),
	("en_US",	"LOC_CIVINFO_PERU_POPULATION",
	"___ (in 2022)"),
	("en_US",	"LOC_CIVINFO_PERU_CAPITAL",
	"___"),
	("en_US",	"LOC_CIVINFO_PERU_LANGUAGE",
	"___"),
	("en_US",	"LOC_CIVINFO_PERU_RELIGION",
	"___"),
	("en_US",	"LOC_CIVINFO_PHILIPPINES_LOCATION",
	"South-East Asia"),
	("en_US",	"LOC_CIVINFO_PHILIPPINES_SIZE",
	"___ square miles (___ square km)"),
	("en_US",	"LOC_CIVINFO_PHILIPPINES_POPULATION",
	"___ (in 2022)"),
	("en_US",	"LOC_CIVINFO_PHILIPPINES_CAPITAL",
	"___"),
	("en_US",	"LOC_CIVINFO_PHILIPPINES_LANGUAGE",
	"___"),
	("en_US",	"LOC_CIVINFO_PHILIPPINES_RELIGION",
	"___"),
	("en_US",	"LOC_CIVINFO_POLAND_LOCATION",
	"Central Europe"),
	("en_US",	"LOC_CIVINFO_POLAND_SIZE",
	"___ square miles (___ square km)"),
	("en_US",	"LOC_CIVINFO_POLAND_POPULATION",
	"___ (in 2022)"),
	("en_US",	"LOC_CIVINFO_POLAND_CAPITAL",
	"___"),
	("en_US",	"LOC_CIVINFO_POLAND_LANGUAGE",
	"___"),
	("en_US",	"LOC_CIVINFO_POLAND_RELIGION",
	"___"),
	("en_US",	"LOC_CIVINFO_PORTUGAL_LOCATION",
	"Southern Europe"),
	("en_US",	"LOC_CIVINFO_PORTUGAL_SIZE",
	"___ square miles (___ square km)"),
	("en_US",	"LOC_CIVINFO_PORTUGAL_POPULATION",
	"___ (in 2022)"),
	("en_US",	"LOC_CIVINFO_PORTUGAL_CAPITAL",
	"___"),
	("en_US",	"LOC_CIVINFO_PORTUGAL_LANGUAGE",
	"___"),
	("en_US",	"LOC_CIVINFO_PORTUGAL_RELIGION",
	"___"),
	("en_US",	"LOC_CIVINFO_ROMANIA_LOCATION",
	"Central Europe"),
	("en_US",	"LOC_CIVINFO_ROMANIA_SIZE",
	"___ square miles (___ square km)"),
	("en_US",	"LOC_CIVINFO_ROMANIA_POPULATION",
	"___ (in 2022)"),
	("en_US",	"LOC_CIVINFO_ROMANIA_CAPITAL",
	"___"),
	("en_US",	"LOC_CIVINFO_ROMANIA_LANGUAGE",
	"___"),
	("en_US",	"LOC_CIVINFO_ROMANIA_RELIGION",
	"___"),
	("en_US",	"LOC_CIVINFO_RUSSIA_LOCATION",
	"East Europe and Asia"),
	("en_US",	"LOC_CIVINFO_RUSSIA_SIZE",
	"___ square miles (___ square km)"),
	("en_US",	"LOC_CIVINFO_RUSSIA_POPULATION",
	"___ (in 2022)"),
	("en_US",	"LOC_CIVINFO_RUSSIA_CAPITAL",
	"___"),
	("en_US",	"LOC_CIVINFO_RUSSIA_LANGUAGE",
	"___"),
	("en_US",	"LOC_CIVINFO_RUSSIA_RELIGION",
	"___"),
	("en_US",	"LOC_CIVINFO_SOUTH_AFRICA_LOCATION",
	"Southern Africa"),
	("en_US",	"LOC_CIVINFO_SOUTH_AFRICA_SIZE",
	"___ square miles (___ square km)"),
	("en_US",	"LOC_CIVINFO_SOUTH_AFRICA_POPULATION",
	"___ (in 2022)"),
	("en_US",	"LOC_CIVINFO_SOUTH_AFRICA_CAPITAL",
	"___"),
	("en_US",	"LOC_CIVINFO_SOUTH_AFRICA_LANGUAGE",
	"___"),
	("en_US",	"LOC_CIVINFO_SOUTH_AFRICA_RELIGION",
	"___"),
	("en_US",	"LOC_CIVINFO_SOUTH_KOREA_LOCATION",
	"East Asia"),
	("en_US",	"LOC_CIVINFO_SOUTH_KOREA_SIZE",
	"___ square miles (___ square km)"),
	("en_US",	"LOC_CIVINFO_SOUTH_KOREA_POPULATION",
	"___ (in 2022)"),
	("en_US",	"LOC_CIVINFO_SOUTH_KOREA_CAPITAL",
	"___"),
	("en_US",	"LOC_CIVINFO_SOUTH_KOREA_LANGUAGE",
	"___"),
	("en_US",	"LOC_CIVINFO_SOUTH_KOREA_RELIGION",
	"___"),
	("en_US",	"LOC_CIVINFO_SPAIN_LOCATION",
	"Southern Europe"),
	("en_US",	"LOC_CIVINFO_SPAIN_SIZE",
	"___ square miles (___ square km)"),
	("en_US",	"LOC_CIVINFO_SPAIN_POPULATION",
	"___ (in 2022)"),
	("en_US",	"LOC_CIVINFO_SPAIN_CAPITAL",
	"___"),
	("en_US",	"LOC_CIVINFO_SPAIN_LANGUAGE",
	"___"),
	("en_US",	"LOC_CIVINFO_SPAIN_RELIGION",
	"___"),
	("en_US",	"LOC_CIVINFO_SUDAN_LOCATION",
	"Northern Africa"),
	("en_US",	"LOC_CIVINFO_SUDAN_SIZE",
	"___ square miles (___ square km)"),
	("en_US",	"LOC_CIVINFO_SUDAN_POPULATION",
	"___ (in 2022)"),
	("en_US",	"LOC_CIVINFO_SUDAN_CAPITAL",
	"___"),
	("en_US",	"LOC_CIVINFO_SUDAN_LANGUAGE",
	"___"),
	("en_US",	"LOC_CIVINFO_SUDAN_RELIGION",
	"___"),
	("en_US",	"LOC_CIVINFO_SWEDEN_LOCATION",
	"Scandinavia (Northern Europe)"),
	("en_US",	"LOC_CIVINFO_SWEDEN_SIZE",
	"___ square miles (___ square km)"),
	("en_US",	"LOC_CIVINFO_SWEDEN_POPULATION",
	"___ (in 2022)"),
	("en_US",	"LOC_CIVINFO_SWEDEN_CAPITAL",
	"___"),
	("en_US",	"LOC_CIVINFO_SWEDEN_LANGUAGE",
	"___"),
	("en_US",	"LOC_CIVINFO_SWEDEN_RELIGION",
	"___"),
	("en_US",	"LOC_CIVINFO_TANZANIA_LOCATION",
	"East Africa"),
	("en_US",	"LOC_CIVINFO_TANZANIA_SIZE",
	"___ square miles (___ square km)"),
	("en_US",	"LOC_CIVINFO_TANZANIA_POPULATION",
	"___ (in 2022)"),
	("en_US",	"LOC_CIVINFO_TANZANIA_CAPITAL",
	"___"),
	("en_US",	"LOC_CIVINFO_TANZANIA_LANGUAGE",
	"___"),
	("en_US",	"LOC_CIVINFO_TANZANIA_RELIGION",
	"___"),
	("en_US",	"LOC_CIVINFO_THAILAND_LOCATION",
	"South-East Asia"),
	("en_US",	"LOC_CIVINFO_THAILAND_SIZE",
	"___ square miles (___ square km)"),
	("en_US",	"LOC_CIVINFO_THAILAND_POPULATION",
	"___ (in 2022)"),
	("en_US",	"LOC_CIVINFO_THAILAND_CAPITAL",
	"___"),
	("en_US",	"LOC_CIVINFO_THAILAND_LANGUAGE",
	"___"),
	("en_US",	"LOC_CIVINFO_THAILAND_RELIGION",
	"___"),
	("en_US",	"LOC_CIVINFO_TURKEY_LOCATION",
	"South-East Europe and the Middle-East"),
	("en_US",	"LOC_CIVINFO_TURKEY_SIZE",
	"___ square miles (___ square km)"),
	("en_US",	"LOC_CIVINFO_TURKEY_POPULATION",
	"___ (in 2022)"),
	("en_US",	"LOC_CIVINFO_TURKEY_CAPITAL",
	"___"),
	("en_US",	"LOC_CIVINFO_TURKEY_LANGUAGE",
	"___"),
	("en_US",	"LOC_CIVINFO_TURKEY_RELIGION",
	"___"),
	("en_US",	"LOC_CIVINFO_UK_LOCATION",
	"West Europe"),
	("en_US",	"LOC_CIVINFO_UK_SIZE",
	"___ square miles (___ square km)"),
	("en_US",	"LOC_CIVINFO_UK_POPULATION",
	"___ (in 2022)"),
	("en_US",	"LOC_CIVINFO_UK_CAPITAL",
	"___"),
	("en_US",	"LOC_CIVINFO_UK_LANGUAGE",
	"___"),
	("en_US",	"LOC_CIVINFO_UK_RELIGION",
	"___"),
	("en_US",	"LOC_CIVINFO_UKRAINE_LOCATION",
	"East Europe"),
	("en_US",	"LOC_CIVINFO_UKRAINE_SIZE",
	"___ square miles (___ square km)"),
	("en_US",	"LOC_CIVINFO_UKRAINE_POPULATION",
	"___ (in 2022)"),
	("en_US",	"LOC_CIVINFO_UKRAINE_CAPITAL",
	"___"),
	("en_US",	"LOC_CIVINFO_UKRAINE_LANGUAGE",
	"___"),
	("en_US",	"LOC_CIVINFO_UKRAINE_RELIGION",
	"___"),
	("en_US",	"LOC_CIVINFO_UZBEKISTAN_LOCATION",
	"Central Asia"),
	("en_US",	"LOC_CIVINFO_UZBEKISTAN_SIZE",
	"___ square miles (___ square km)"),
	("en_US",	"LOC_CIVINFO_UZBEKISTAN_POPULATION",
	"___ (in 2022)"),
	("en_US",	"LOC_CIVINFO_UZBEKISTAN_CAPITAL",
	"___"),
	("en_US",	"LOC_CIVINFO_UZBEKISTAN_LANGUAGE",
	"___"),
	("en_US",	"LOC_CIVINFO_UZBEKISTAN_RELIGION",
	"___"),
	("en_US",	"LOC_CIVINFO_VENEZUELA_LOCATION",
	"South America"),
	("en_US",	"LOC_CIVINFO_VENEZUELA_SIZE",
	"___ square miles (___ square km)"),
	("en_US",	"LOC_CIVINFO_VENEZUELA_POPULATION",
	"___ (in 2022)"),
	("en_US",	"LOC_CIVINFO_VENEZUELA_CAPITAL",
	"___"),
	("en_US",	"LOC_CIVINFO_VENEZUELA_LANGUAGE",
	"___"),
	("en_US",	"LOC_CIVINFO_VENEZUELA_RELIGION",
	"___"),
	("en_US",	"LOC_CIVINFO_VIETNAM_LOCATION",
	"South-East Asia"),
	("en_US",	"LOC_CIVINFO_VIETNAM_SIZE",
	"___ square miles (___ square km)"),
	("en_US",	"LOC_CIVINFO_VIETNAM_POPULATION",
	"___ (in 2022)"),
	("en_US",	"LOC_CIVINFO_VIETNAM_CAPITAL",
	"___"),
	("en_US",	"LOC_CIVINFO_VIETNAM_LANGUAGE",
	"___"),
	("en_US",	"LOC_CIVINFO_VIETNAM_RELIGION",
	"___"),
		
-- History
	("en_US",	"LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_ICELAND_CHAPTER_HISTORY_PARA_1",
	"Iceland (Icelandic: Ísland) is a Nordic island country in the North Atlantic Ocean and in the Arctic Ocean, the most sparsely populated country in Europe. Iceland's capital and largest city is Reykjavík, which (along with its surrounding areas) is home to over 65% of the population. Iceland is the biggest part of the Mid-Atlantic Ridge that rises above sea level, and its central volcanic plateau is erupting almost constantly. The interior consists of a plateau characterised by sand and lava fields, mountains, and glaciers, and many glacial rivers flow to the sea through the lowlands. Iceland is warmed by the Gulf Stream and has a temperate climate, despite a high latitude just outside the Arctic Circle. Its high latitude and marine influence keep summers chilly, and most of its islands have a polar climate."),
	("en_US",	"LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_ICELAND_CHAPTER_HISTORY_PARA_2",
	"According to the ancient manuscript Landnámabók, the settlement of Iceland began in 874 AD when the Norwegian chieftain Ingólfr Arnarson became the first permanent settler on the island. In the following centuries, Norwegians, and to a lesser extent, other Scandinavians, immigrated to Iceland, bringing with them thralls (i.e., slaves or serfs) of Gaelic origin."),
	("en_US",	"LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_ICELAND_CHAPTER_HISTORY_PARA_3",
	"The island was governed as an independent commonwealth under the native parliament, the Althing, one of the world's oldest functioning legislative assemblies. Following a period of civil strife, Iceland acceded to Norwegian rule in the 13th century. The establishment of the Kalmar Union in 1397 united the kingdoms of Norway, Denmark, and Sweden. Iceland, as a result, followed Norway's integration into that union, coming under Danish rule after Sweden seceded from the union in 1523. The Danish kingdom forcefully introduced Lutheranism to Iceland in 1550."),
	("en_US",	"LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_ICELAND_CHAPTER_HISTORY_PARA_4",
	"In the wake of the French Revolution and the Napoleonic Wars, Iceland's struggle for independence took form and culminated in independence in 1918 with the establishment of the Kingdom of Iceland, sharing through a personal union the incumbent monarch of Denmark. During the occupation of Denmark in World War II, Iceland voted overwhelmingly to become a republic in 1944, thus ending the remaining formal ties with Denmark. Although the Althing was suspended from 1799 to 1845, the island republic has been credited with sustaining the world's oldest and longest-running parliament."),
	("en_US",	"LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_ICELAND_CHAPTER_HISTORY_PARA_5",
	"Until the 20th century, Iceland relied largely on subsistence fishing and agriculture. Industrialization of the fisheries and Marshall Plan aid following World War II brought prosperity, and Iceland became one of the wealthiest and most developed nations in the world. It became a part of the European Economic Area in 1994; this further diversified the economy into sectors such as finance, biotechnology, and manufacturing."),
	("en_US",	"LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_ICELAND_CHAPTER_HISTORY_PARA_6",
	"Iceland has a market economy with relatively low taxes, compared to other OECD countries, as well as the highest trade union membership in the world. It maintains a Nordic social welfare system that provides universal health care and tertiary education for its citizens. Iceland ranks high in democracy and equality indexes, ranking third in the world by median wealth per adult. In 2021, it was ranked as the third-most developed country in the world by the United Nations' Human Development Index, and it ranks first on the Global Peace Index. Iceland runs almost completely on renewable energy, but is the only NATO member with no standing army, with a lightly armed coast guard."),
	("en_US",	"LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_MADAGASCAR_CHAPTER_HISTORY_PARA_1",
	"Madagascar (Malagasy: Madagasikara), officially the Republic of Madagascar (Malagasy: Repoblikan'i Madagasikara), is an island country in the Indian Ocean, approximately 400 kilometres (250 miles) off the coast of East Africa across the Mozambique Channel. At 592,800 square kilometres (228,900 sq mi) Madagascar is the world's second-largest island country, after Indonesia. The nation is home to around 30 million inhabitants and consists of the island of Madagascar (the fourth-largest island in the world), along with numerous smaller peripheral islands. Following the prehistoric breakup of the supercontinent Gondwana, Madagascar split from the Indian subcontinent around 90 million years ago, allowing native plants and animals to evolve in relative isolation. Consequently, Madagascar is a biodiversity hotspot; over 90% of its wildlife is endemic."),
	("en_US",	"LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_MADAGASCAR_CHAPTER_HISTORY_PARA_2",
	"Human settlement of Madagascar occurred during or before the mid first millennium AD by Austronesian peoples, presumably arriving on outrigger canoes from present-day Indonesia. These were joined around the 9th century AD by Bantu migrants crossing the Mozambique Channel from East Africa. Other groups continued to settle on Madagascar over time, each one making lasting contributions to Malagasy cultural life. The Malagasy ethnic group is often divided into 18 or more subgroups, of which the largest are the Merina of the central highlands."),
	("en_US",	"LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_MADAGASCAR_CHAPTER_HISTORY_PARA_3",
	"Upon its emergence in the early 17th century, the highland kingdom of Imerina was initially a minor power relative to the larger coastal kingdoms and grew even weaker in the early 18th century when King Andriamasinavalona divided it among his four sons. Following almost a century of warring and famine, Imerina was reunited in 1793 by King Andrianampoinimerina (1787–1810). From his initial capital Ambohimanga, and later from the Rova of Antananarivo, this Merina king rapidly expanded his rule over neighboring principalities. His ambition to bring the entire island under his control was largely achieved by his son and successor, King Radama I (1810–28), who was recognized by the British government as King of Madagascar. Radama concluded a treaty in 1817 with the British governor of Mauritius to abolish the lucrative slave trade in return for British military and financial assistance. Artisan missionary envoys from the London Missionary Society began arriving in 1818 and included such key figures as James Cameron, David Jones and David Griffiths, who established schools, transcribed the Malagasy language using the Roman alphabet, translated the Bible, and introduced a variety of new technologies to the island."),
	("en_US",	"LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_MADAGASCAR_CHAPTER_HISTORY_PARA_4",
	"Until the late 18th century, the island of Madagascar was ruled by a fragmented assortment of shifting sociopolitical alliances. Beginning in the early 19th century, most of the island was united and ruled as the Kingdom of Madagascar by a series of Merina nobles. The monarchy ended in 1897 when the island was absorbed into the French colonial empire, from which the island gained independence in 1960. The autonomous state of Madagascar has since undergone four major constitutional periods, termed republics. Since 1992, the nation has officially been governed as a constitutional democracy from its capital at Antananarivo. However, in a 2009 political crisis, president Marc Ravalomanana was made to resign and presidential power was transferred in March 2009 to Andry Rajoelina. Constitutional governance was restored in January 2014, when Hery Rajaonarimampianina was named president following a 2013 election deemed fair and transparent by the international community. Madagascar is a member of the United Nations, the African Union (AU), the Southern African Development Community (SADC), and the Organisation Internationale de la Francophonie."),
	("en_US",	"LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_MADAGASCAR_CHAPTER_HISTORY_PARA_5",
	"Madagascar belongs to the group of least developed countries, according to the United Nations. Malagasy and French are both official languages of the state. Christianity is the predominant religion in the country, but a significant minority still practice traditional faiths. Ecotourism and agriculture, paired with greater investments in education, health, and private enterprise, are key elements of Madagascar's development strategy. Under Ravalomanana, these investments produced substantial economic growth, but the benefits were not evenly spread throughout the population, producing tensions over the increasing cost of living and declining living standards among the poor and some segments of the middle class. The economy was weakened by the 2009 political crisis, and as of 2017, quality of life remains low for the majority of the Malagasy population. Madagascar is experiencing an ongoing famine, which experts argue is the first to be caused entirely by climate change."),
	("en_US",	"LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_PAPUA_NEW_GUINEA_CHAPTER_HISTORY_PARA_1",
	"Currently a work-in-progress country for Basic Modern Civilizations!"),
	("en_US",	"LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_PAPUA_NEW_GUINEA_CHAPTER_HISTORY_PARA_2",
	"Papua New Guinea (abbreviated PNG), officially the Independent State of Papua New Guinea, is a country in Oceania that comprises the eastern half of the island of New Guinea and its offshore islands in Melanesia (a region of the southwestern Pacific Ocean north of Australia). Its capital, located along its southeastern coast, is Port Moresby. The country is the world's third largest island country, with an area of 462,840 km2 (178,700 sq mi)."),
	("en_US",	"LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_PAPUA_NEW_GUINEA_CHAPTER_HISTORY_PARA_3",
	"At the national level, after being ruled by three external powers since 1884, including nearly 60 years of Australian administration starting during World War I, Papua New Guinea established its sovereignty in 1975. It became an independent Commonwealth realm in 1975 with Elizabeth II as its queen. It also became a member of the Commonwealth of Nations in its own right."),
	("en_US",	"LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_PAPUA_NEW_GUINEA_CHAPTER_HISTORY_PARA_2",
	"The sovereign state is classified as a developing economy by the International Monetary Fund; nearly 40% of the population are subsistence farmers, living relatively independently of the cash economy. Their traditional social groupings are explicitly acknowledged by the Papua New Guinea Constitution, which expresses the wish for 'traditional villages and communities to remain as viable units of Papua New Guinean society' and protects their continuing importance to local and national community life. Papua New Guinea has been an observer state in the Association of Southeast Asian Nations (ASEAN) since 1976, and has filed its application for full membership status. It is a full member of the Commonwealth of Nations, the Pacific Community, and the Pacific Islands Forum."),
	("en_US",	"LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_PAPUA_NEW_GUINEA_CHAPTER_HISTORY_PARA_2",
	"The country is believed to be the home of many undocumented species of plants and animals. There are 839 known languages of Papua New Guinea, one of the most linguistically diverse countries in the world. As of 2019, it is also the most rural, as only 13.25% of its people live in urban centres. Most of the population of more than 8 million people live in customary communities. Although government estimates have placed the country's population at 9.4 million, it was reported in December 2022 that a yet-to-be-published study suggests the true population is close to 17 million."),
	("en_US",	"LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUDAN_CHAPTER_HISTORY_PARA_1",
	"Sudan (Arabic: السودان), officially the Republic of the Sudan (Arabic: جمهورية السودان), is a country in Northeast Africa. It shares borders with the Central African Republic to the southwest, Chad to the west, Egypt to the north, Eritrea to the northeast, Ethiopia to the southeast, Libya to the northwest, South Sudan to the south and the Red Sea. It has a population of 45.70 million people as of 2022 and occupies 1,886,068 square kilometres (728,215 square miles), making it Africa's third-largest country by area, and the third-largest by area in the Arab League. It was the largest country by area in Africa and the Arab League until the secession of South Sudan in 2011, since which both titles have been held by Algeria. Its capital is Khartoum and its most populated city is Omdurman (part of the metropolitan area of Khartoum)."),
	("en_US",	"LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUDAN_CHAPTER_HISTORY_PARA_1",
	"Sudan's history goes back to the Pharaonic period, witnessing the Kingdom of Kerma (c. 2500–1500 BC), the subsequent rule of the Egyptian New Kingdom (c. 1500 BC–1070 BC) and the rise of the Kingdom of Kush (c. 785 BC–350 AD), which would in turn control Egypt itself for nearly a century. After the fall of Kush, the Nubians formed the three Christian kingdoms of Nobatia, Makuria, and Alodia, with the latter two lasting until around 1500. Between the 14th and 15th centuries, most of Sudan was gradually settled by Arab nomads. From the 16th to the 19th centuries, central and eastern Sudan were dominated by the Funj sultanate, while Darfur ruled the west and the Ottomans the east."),
	("en_US",	"LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUDAN_CHAPTER_HISTORY_PARA_1",
	"During the Mamluk and Ottoman periods, slave trade played a big role and was demanded from the Sudanese Kashif as the regular remittance of tribute. In 1811, Mamluks established a state at Dunqulah as a base for their slave trading. Under Turco-Egyptian rule of Sudan after the 1820s, the practice of trading slaves was entrenched along a north–south axis, with slave raids taking place in southern parts of the country and slaves being transported to Egypt and the Ottoman empire."),
	("en_US",	"LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUDAN_CHAPTER_HISTORY_PARA_1",
	"From the early 19th century, the entirety of Sudan was conquered by the Ottomans under the Muhammad Ali dynasty. It was under Turkish rule that Sudan acquired its modern borders and began the process of political, agricultural, and economic development. In 1881, nationalist sentiment in Egypt led to the Orabi Revolt, 'weakening' the power of the Egyptian monarchy, and eventually leading to the occupation of Egypt by the United Kingdom. At the same time, religious-nationalist fervour in Sudan erupted in the Mahdist Uprising led by the self-proclaimed Mahdi Muhammad Ahmad, and resulting in the establishment of the Caliphate of Omdurman. The Mahdist forces were eventually defeated by a joint Egyptian-British military force, restoring the authority of the Egyptian monarch. However, Egyptian sovereignty in Sudan would henceforth be rather nominal, as the true power in both Egypt and Sudan was now the United Kingdom. In 1899, under British pressure, Egypt agreed to share sovereignty over Sudan with the United Kingdom as a condominium. In effect, Sudan was governed as a British possession. The 20th century saw the growth of both Egyptian and Sudanese nationalism focusing on ending the United Kingdom's occupation. The Egyptian revolution of 1952 toppled the monarchy and demanded the withdrawal of British forces from all of Egypt and Sudan. Muhammad Naguib, one of the two co-leaders of the revolution, and Egypt's first President, who was half-Sudanese and had been raised in Sudan, made securing Sudanese independence a priority of the revolutionary government. The following year, under Egyptian and Sudanese pressure, the United Kingdom agreed to Egypt's demand for both governments to terminate their shared sovereignty over Sudan and to grant Sudan independence. On 1 January 1956, Sudan was duly declared an independent state."),
	("en_US",	"LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUDAN_CHAPTER_HISTORY_PARA_1",
	"After Sudan became independent, the Jaafar Nimeiry regime began Islamist rule. This exacerbated the rift between the Islamic North, the seat of the government, and the Animists and Christians in the South. Differences in language, religion, and political power erupted in a civil war between government forces, influenced by the National Islamic Front (NIF), and the southern rebels, whose most influential faction was the Sudan People's Liberation Army (SPLA), which eventually led to the independence of South Sudan in 2011. Between 1989 and 2019, Sudan experienced a 30-year-long military dictatorship led by Omar al-Bashir, who was accused of human rights abuses, including torture, persecution of minorities, allegations of sponsoring global terrorism, and ethnic genocide due to its actions in the War in the Darfur region that broke out in 2003. Overall, the regime's actions killed an estimated 300,000 to 400,000 people. Protests erupted in 2018, demanding Bashir's resignation, which resulted in a coup d'état on 11 April 2019 and Bashir's imprisonment."),
	("en_US",	"LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUDAN_CHAPTER_HISTORY_PARA_1",
	"Islam was Sudan's state religion and Islamic laws were applied from 1983 until 2020 when the country became a secular state. The economy has been described as lower-middle income, with over 35% population living in poverty, largely relies on agriculture due to long-term international sanctions and isolation, as well as a long history of internal instability and factional violence, to some extent on oil production in the oil fields of South Sudan. Sudan is a member of the United Nations, the Arab League, African Union, COMESA, Non-Aligned Movement and the Organisation of Islamic Cooperation."),
	("en_US",	"LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TANZANIA_CHAPTER_HISTORY_PARA_1",
	"Tanzania, officially the United Republic of Tanzania (Swahili: Jamhuri ya Muungano wa Tanzania), is a country in East Africa within the African Great Lakes region. It borders Uganda to the north; Kenya to the northeast; Comoro Islands and the Indian Ocean to the east; Mozambique and Malawi to the south; Zambia to the southwest; and Rwanda, Burundi, and the Democratic Republic of the Congo to the west. Mount Kilimanjaro, Africa's highest mountain, is in northeastern Tanzania. According to the United Nations, Tanzania has a population of 63.59 million, making it the most populous country located entirely south of the equator."),
	("en_US",	"LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TANZANIA_CHAPTER_HISTORY_PARA_2",
	"Many important hominid fossils have been found in Tanzania, such as 6-million-year-old Pliocene hominid fossils. The genus Australopithecus ranged across Africa between 4 and 2 million years ago, and the oldest remains of the genus Homo are found near Lake Olduvai. Following the rise of Homo erectus 1.8 million years ago, humanity spread all over the Old World, and later in the New World and Australia under the species Homo sapiens. H. sapiens also overtook Africa and absorbed the older species of humanity."),
	("en_US",	"LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TANZANIA_CHAPTER_HISTORY_PARA_3",
	"Later in the Stone and Bronze Age, prehistoric migrations into Tanzania included Southern Cushitic speakers who moved south from present-day Ethiopia; Eastern Cushitic people who moved into Tanzania from north of Lake Turkana about 2,000 and 4,000 years ago; and the Southern Nilotes, including the Datoog, who originated from the present-day South Sudan–Ethiopia border region between 2,900 and 2,400 years ago. These movements took place at about the same time as the settlement of the Mashariki Bantu from West Africa in the Lake Victoria and Lake Tanganyika areas. They subsequently migrated across the rest of Tanzania between 2,300 and 1,700 years ago."),
	("en_US",	"LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TANZANIA_CHAPTER_HISTORY_PARA_4",
	"Bantu-speakers built farming and trade villages along the Tanzanian coast from the outset of the first millennium. Archaeological finds at Fukuchani, on the north-west coast of Zanzibar, indicate a settled agricultural and fishing community from the 6th century CE at the latest. The considerable amount of daub found indicates timber buildings, and shell beads, bead grinders, and iron slag have been found at the site. There is evidence for limited engagement in long-distance trade: a small amount of imported pottery has been found, less than 1% of total pottery finds, mostly from the Gulf and dated to the 5th to 8th century. The similarity to contemporary sites such as Mkokotoni and Dar es Salaam indicate a unified group of communities that developed into the first centre of coastal maritime culture. The coastal towns appear to have been engaged in Indian Ocean and inland African trade at this early period. Trade rapidly increased in importance and quantity beginning in the mid-8th century and by the close of the 10th century Zanzibar was one of the central Swahili trading towns."),
	("en_US",	"LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TANZANIA_CHAPTER_HISTORY_PARA_5",
	"Growth in Egyptian and Persian shipping from the Red Sea and the Persian Gulf revitalised Indian Ocean trade, particularly after the Fatimid Caliphate relocated to Fustat (Cairo). Swahili agriculturalists built increasingly dense settlements to tap into trade, these forming the earliest Swahili city-states. The Venda-Shona Kingdoms of Mapungubwe and Zimbabwe in South Africa and Zimbabwe, respectively, became a major producer of gold around this same period. Economic, social, and religious power was increasingly vested in Kilwa, Tanzania's major medieval city-state. Kilwa controlled a number of smaller ports stretching down to modern-day Mozambique. Sofala became the major gold emporium and Kilwa grew rich off the trade, lying at the southern end of the Indian Ocean Monsoons. Kilwa's major rivals lay to the north, in modern-day Kenya, namely Mombasa and Malindi. Kilwa remained the major power in East Africa until the arrival of the Portuguese at the end of the 15th century."),
	("en_US",	"LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TANZANIA_CHAPTER_HISTORY_PARA_6",
	"German rule began in mainland Tanzania during the late 19th century when Germany formed German East Africa. This was followed by British rule after World War I. The mainland was governed as Tanganyika, with the Zanzibar Archipelago remaining a separate colonial jurisdiction. Following their respective independence in 1961 and 1963, the two entities merged in 1964 to form the United Republic of Tanzania. Tanganyika joined the British Commonwealth in 1961 and Tanzania remains a member of the Commonwealth as a unified republic."),
	("en_US",	"LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TANZANIA_CHAPTER_HISTORY_PARA_7",
	"Tanzania's population is composed of about 120 ethnic, linguistic, and religious groups. The sovereign state of Tanzania is a presidential constitutional republic and since 1996 its official capital city has been Dodoma where the president's office, the National Assembly, and all government ministries are located. Dar es Salaam, the former capital, retains most government offices and is the country's largest city, principal port, and leading commercial centre. Tanzania is a de facto one-party state with the democratic socialist Chama Cha Mapinduzi party in power."),
	("en_US",	"LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TANZANIA_CHAPTER_HISTORY_PARA_8",
	"Tanzania is mountainous and densely forested in the north-east, where Mount Kilimanjaro is located. Three of Africa's Great Lakes are partly within Tanzania. To the north and west lie Lake Victoria, Africa's largest lake, and Lake Tanganyika, the continent's deepest lake, known for its unique species of fish. To the south lies Lake Malawi. The eastern shore is hot and humid, with the Zanzibar Archipelago just offshore. The Menai Bay Conservation Area is Zanzibar's largest marine protected area. The Kalambo Falls, located on the Kalambo River at the Zambian border, is the second-highest uninterrupted waterfall in Africa."),
	("en_US",	"LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TANZANIA_CHAPTER_HISTORY_PARA_9",
	"Christianity is the largest religion in Tanzania, but there are also substantial Muslim and animist minorities. Over 100 different languages are spoken in Tanzania, making it the most linguistically diverse country in East Africa. The country does not have a de jure official language, although the national language is Swahili. Swahili is used in parliamentary debate, in the lower courts, and as a medium of instruction in primary school. English is used in foreign trade, in diplomacy, in higher courts, and as a medium of instruction in secondary and higher education; although the Tanzanian government is planning to discontinue English as the primary language of instruction, it will be available as an optional course. Approximately 10% of Tanzanians speak Swahili as a first language, and up to 90% speak it as a second language.");